### ISSUE TITLE
get a better icon

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#115]
I like my current icon but lets be real it's made in MSpaint.... I really need a better one.

I'm disinclined to spend money on a project that hasn't earned me a dime*, but if I did there are some good webcomic artists that could probably do it for 20$

* On the other hand, there's the phrase "you gotta spend money to make money"

**Comment by Almenon** [comment]
An [ouroboros](https://en.wikipedia.org/wiki/Ouroboros) would be cool.  Or I could just get a better cat icon.

**Comment by gllms** [comment]
@Almenon I designed a cat icon very loosely based on the original. I am not sure what emotion the pixel cat is feeling, so I made a few variations
![Untitled-1](https://user-images.githubusercontent.com/19732805/94372025-da58aa80-00fa-11eb-8200-f3103c260bdf.png)

**Comment by Almenon** [comment]
@gllms wow, thanks! Those images look really nice, so minimalist yet so expressive! I can definitely replace my marketplace icon with this.

https://i.imgur.com/9KPnRE5.png <- yasss

I'll have to give the other emotions a try as well to see how they look. Can you upload the files individually please? I tried using [ShareX ](https://getsharex.com/) scren capture to take pictures of them individually as a hacky way of splitting it but I definitely didn't get a perfect rectangle 🙈 

The status bar is more tricky. Unfortunately the status bar at the top is so darn small it is really hard to distinguish between the "running" state and "closed" state using the cat icons. Maybe I should use a different icon for running/closed? I can't use a normal start/stop icon because other extensions might use the same one 😢 Any ideas?

can openAREPLstate: https://i.imgur.com/fTGky06.png
can close AREPL state: 
![image](https://user-images.githubusercontent.com/13080965/95546203-d22f2380-09b4-11eb-9c54-25645adb5ecd.png)

**Comment by gllms** [comment]
I'm happy you like it!
Here are the separate images:
<p align="center">
<img src="https://user-images.githubusercontent.com/19732805/95555876-b9555b00-0a12-11eb-85e6-3d544575b94f.png" width="100px"/>
<img src="https://user-images.githubusercontent.com/19732805/95555880-ba868800-0a12-11eb-8133-8d7203d732af.png" width="100px"/>
<img src="https://user-images.githubusercontent.com/19732805/95555884-bbb7b500-0a12-11eb-9411-9a0193b9399a.png" width="100px"/>
</p>

Outlined versions could be used for closed, just like currently is the case.

<p align="center">
<img src="https://user-images.githubusercontent.com/19732805/95555888-bd817880-0a12-11eb-9b19-da8d0119e69a.png" width="100px"/>
<img src="https://user-images.githubusercontent.com/19732805/95555892-beb2a580-0a12-11eb-8827-83676ce07829.png" width="100px"/>
<img src="https://user-images.githubusercontent.com/19732805/95555897-bfe3d280-0a12-11eb-8af5-57c797cee1fd.png" width="100px"/>
</p>

**Comment by gllms** [comment]
You are allowed to use SVG as statusbar icons, right?. In that case, here they are. The file size of the SVGs is smaller (~2KB instead of ~40KB)
[Cat SVG.zip](https://github.com/Almenon/AREPL-vscode/files/5353927/Cat.SVG.zip)

**Comment by Almenon** [comment]
> You are allowed to use SVG as status bar icons, right? 

I think so. Thanks!  I've added the icons in 6af20776f6d70f801ae7052990169839741831fe - it may be a while before I publish a new release of AREPL with the icons.

**Comment by Almenon** [comment]
I just released a new version of AREPL with your icon, thanks!

https://marketplace.visualstudio.com/items?itemName=almenon.arepl
