### ISSUE TITLE
UnicodeEncodeError: 'utf-8' 

### ISSUE THREAD

**Issue by liren5257** [Almenon/AREPL-vscode#149]
have a problem when i input some chinese in my code 
the bug is  "UnicodeEncodeError: 'utf-8' codec can't encode character '\udcab' in position 19: surrogates not allowed"
when write some  note in my code just like  "#this is a main file 这是个主文件" the bug will trigger

**Comment by liren5257** [comment]
and this bug will trigger when print() the chinese  just like "print('这是个主文件')"

**Comment by liren5257** [comment]
windows 10  will trigger  this bug  
MAC os  is OK

**Comment by Almenon** [comment]
I just tried it and it worked in both scenarios :/

What version python do you have?

Also can you send me a screenshot of the file and arepl please? Seeing it might help.

**Comment by liren5257** [comment]
the normal ：
[https://drive.google.com/open?id=1_z-CR6QWmfxF5TblAXuOHx0IW6LqhjED](url)
the bug：
[https://drive.google.com/open?id=1LUGDTD171P9ApzjzYSbjhycj15Ll0vpg](url)
py file：
[https://drive.google.com/open?id=19rkxvIUXk6949GNOKdUY9qkkaSrPCfVR](url)
THX for your read!

**Comment by Almenon** [comment]
Thanks.  By the way, for formatting links you should do it like this:

\[link text\](https://www.websiteToGoTo.com)

For example, I edited your comment to have below format:

\[https://drive.google.com/open?id=19rkxvIUXk6949GNOKdUY9qkkaSrPCfVR\](https://drive.google.com/open?id=19rkxvIUXk6949GNOKdUY9qkkaSrPCfVR)

**Comment by lolimay** [comment]
> windows 10 will trigger this bug
> MAC os is OK

I think this problem has nothing to do with AREPL. Maybe you need to add utf-8 comment header to force source file apply utf-8 coding.
````
# coding=utf-8
````

**Comment by Almenon** [comment]
I was finally able to replicate this problem with the following:

```python
# coding=utf-8
#㍨
```

Unfortunately the utf-8 comment header does not help

Also I have no idea how to fix this :(

**Comment by Almenon** [comment]
note to self: once this is fixed tweet to https://twitter.com/CClF3/status/1156481798131421184 to let them know.

**Comment by hsx2117** [comment]
I have the same problem in Mac :(

**Comment by hsx2117** [comment]
> I have the same problem in Mac :(

But I remmber my python script that include Chinese note before was ok.
So i use that old script for AREPL, it still ok!
And then i copy the script content to new script file, it occurs same utf-8 codec problem that described above.

**Comment by hsx2117** [comment]
> > I have the same problem in Mac :(
> 
> But I remmber my python script that include Chinese note before was ok.
> So i use that old script for AREPL, it still ok!
> And then i copy the script content to new script file, it occurs same utf-8 codec problem that described above.

I found the trigger reason. When i delete the vscode workplace describe file, it is ok for my script included Chinese note.

**Comment by Almenon** [comment]
Made some progress on this, posting notes here:

```python
import sys
print(sys.stdout.encoding) # should be utf8

print(f'sys default encoding is  {sys.getdefaultencoding()}')
print(f'stdout encoding is {sys.stdout.encoding}')
print('printing eggplant emoji: 🍆')
exec('print("🍆")')
# The above works despite not working in arepl...

"""
encoding error happens when exec is called. Maybe when exec tries to compile string?
Note that it happens even if commented out so it's not due to code being ran
I tried .encode('utf8') and .encode('utf8','surrogateescape') but neither worked :(

Maybe it's because sys.stdin.encoding is set to cp1252!! I just need to set it right in node!

    with open("C:\\dev\\arepl2.txt", 'w') as f:
        f.write(traceback.format_exc())
"""
```

**Comment by Almenon** [comment]
I solved it! :D 

Take that unicode errors!

I looked into it and found that the python-shell library I use in the backend already uses utf8 encoding, so it wasn't node's fault. After reading through the python docs I found out that in python pipes use the system locale encoding (cp1252 in case of windows). The console device uses utf8 which is why python works correctly in the terminal. You can create a .env file in the root folder of your workspace with `PYTHONIOENCODING=utf8` (see explanation of var in [python docs](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING)) and emojis and other unicode goodness will work in AREPL :)

Of course having to create a .env file in every project would be annoying - I'll release a update to arepl that sets PYTHONIOENCODING=utf8 automatically.

**Comment by Almenon** [comment]
Next release should be coming shortly. Just need a teeny tiny bit more testing

**Comment by Almenon** [comment]
AREPL 1.0.24 should fix this problem on windows. Not sure about mac.

@liren5257 @hsx2117 @lolimay can you verify if it works now please?
