### ISSUE TITLE
File directory added to sys.path on every change

### ISSUE THREAD

**Issue by Radivarig** [Almenon/AREPL-vscode#152]
This seem to not happen when there is no import.
```py
import sys
print (sys.path)
from something import *
```
Python 3.6.7
OS: nixos 18.09.1789.11c9922a7d5 (Jellyfish)

**Comment by Almenon** [comment]
I tried your example on windows but I'm not getting that problem.  Does this happen when importing standard modules like json?

**Comment by Radivarig** [comment]
Hm, it happens only when compiler is throwing error. Try random variable name and delete one by one character

**Comment by Almenon** [comment]
Fixed. I just need a try/finally around the yield in script_path
