### ISSUE TITLE
Conflicts with python extension

### ISSUE THREAD

**Issue by lolimay** [Almenon/AREPL-vscode#199]
Hi, when I disabled [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension and found that AREPL works well, but once I enabled Python extension,  its output will be like this:
````bash
Print Output:
  File "/home/lolimay/.vscode/extensions/almenon.arepl-1.0.10/node_modules/arepl-backend/python/pythonEvaluator.py", line 169
    raise StopIteration("There is no more input") from None
                                                     ^
SyntaxError: invalid syntax
````
I guess there should be some conflicts between these two extensions. 

System Info: deepin 15.9 (based on debian 9)
VS Code Version: 1.31.1
AREPL Version: 1.0.10

**Comment by lolimay** [comment]
Any help will be appreciated!

**Comment by lolimay** [comment]
![peek 2019-03-02 16-33](https://user-images.githubusercontent.com/32427260/53679563-f91d7200-3d08-11e9-980e-4d0f81f549fb.gif)

**Comment by lolimay** [comment]
I did some experiments by installing some other versions of AREPL,  I am sure that this problem was introduced from version **1.0.8** because version 1.0.7 all works well.

**Comment by Almenon** [comment]
There's no conflicts here - in fact, arepl now _integrates_ with the python extension.  The problem is that you have your python extension set up to use Python 2.  Switch your python path to python 3 and you should be good.

**Comment by Almenon** [comment]
alternatively, if for some reason you want to continue using python 2 in python extension, you can set arepl.pythonPath to point to your python 3 installation.

**Comment by Almenon** [comment]
no response - I'm assuming fixed? Closing, please let me know if it's not fixed. Or if it is fixed.

**Comment by yanisurbis** [comment]
Just put python3 path in extension settings if you have this problem
