### ISSUE TITLE
Remove variables object

### ISSUE THREAD

**Issue by Ciappp** [Almenon/AREPL-vscode#231]
Hi, i would to remove the variables object from the python preview of AREPL. How could I do?

**Comment by Almenon** [comment]
Are you talking about this?

https://i.imgur.com/gLB5CXS.png

Why do you want to remove it?

**Comment by Almenon** [comment]
I'm assuming https://github.com/Almenon/AREPL-vscode/issues/232 will satisfy you -  closing. It will be released next update :)
