### ISSUE TITLE
can't use AREPL, getting error

### ISSUE THREAD

**Issue by CeibaSheep** [Almenon/AREPL-vscode#249]
File "/home/ceiba/.vscode/extensions/almenon.arepl-1.0.14/node_modules/arepl-backend/python/pythonEvaluator.py", line 169
    raise StopIteration("There is no more input") from None
                                                     ^
SyntaxError: invalid syntax

**Comment by Almenon** [comment]
That's because you're using python 2 - change either python.pythonPath or arepl.pythonPath to point to a python 3 interpreter and it should work :)

**Comment by Almenon** [comment]
closing - let me know if the error still happens.
