### ISSUE TITLE
AREPL gives an error when attempting to evaluate code

### ISSUE THREAD

**Issue by agracy2246** [Almenon/AREPL-vscode#254]
So I downloaded AREPL for python and I am trying to get it working.

I write simple code like a = 5+5, right-click the editor title and I have tried both eval in new a current doc.

I only get the error 

> Print Output:
>   File "/home/eng1nerd/.vscode/extensions/almenon.arepl-1.0.14/node_modules/arepl-backend/python/pythonEvaluator.py", line 169
>     raise StopIteration("There is no more input") from None
>                                                      ^
> SyntaxError: invalid syntax

I don't know what this means, and I am hoping someone can help me solve this.

**Comment by Almenon** [comment]
It means arepl was launched with python 2.  Change either python.pythonpath or arepl.pythonpath to point to python 3 and it should work :)

**Comment by Almenon** [comment]
It looks like you're using a Linux OS which means python is python2 by default - I suggest specifying python3 for the python path.

**Comment by Almenon** [comment]
closing but feel free to comment if you have any trouble.
