### ISSUE TITLE
Setting font size

### ISSUE THREAD

**Issue by nbahmanyar** [Almenon/AREPL-vscode#257]
I'm using version 1.0.14 of AREPL for python for VS Code, and I can't seem to find how to change the font size of the AREPL tab.

VS Code version is 1.34.0

I tried changing various font size values in the VS Code settings but perhaps I'm missing something. Is there a way to change font size in the AREPL tab?

**Comment by Almenon** [comment]
You can change the font size of all text, but not specifically in the arepl tab. I'll add in that feature :)

**Comment by Almenon** [comment]
I added a customCSS setting you can use to inject your own style into AREPL. For example, if you wanted larger text you could do `span { font-size: 40px; }`

I'll let you know when next release with this feature goes out

**Comment by nbahmanyar** [comment]
Great, thanks a lot!

**Comment by Almenon** [comment]
I just released a new version of arepl with this feature.

**Comment by eddyg** [comment]
Thanks for AREPL!

FWIW, I'm setting this so the AREPL "Print Output" and "Variables" sections match the editor prefs:

```json
    "AREPL.customCSS": ".print { font-size: var(--vscode-editor-font-size); } .renderjson { font-family: var(--vscode-editor-font-family); font-size: var(--vscode-editor-font-size); }",
```

(Any reason this couldn't be the default?)

**Comment by Almenon** [comment]
@eddyg Sure, that makes sense to me. I've set this as the default for the latest release of AREPL (2.0.4)
