### ISSUE TITLE
Print Output turns black

### ISSUE THREAD

**Issue by ilnerdchuck** [Almenon/AREPL-vscode#259]
The output code turns in Arial Black instantly after i open it, and despite the "Demo" it shows the print output before the variables. But if i open the preview and run the code and get the issue then i change theme it gets the right theme color, but as soon as i run again it get black. i've tryed the stock theme also and nothing changes. Running on Debian Coder a web distro of VsStudio

**Comment by Almenon** [comment]
The demo gif is long out of date. Print output now shows above variable output by default, I feel that it works better that way. You can set `AREPL.printResultPlacement` to "bottom" if you wish to change it.

Can you show me a image/gif/video of what happens please? I can't get a clear understanding of the problem.

**Comment by ilnerdchuck** [comment]
Ok i thought it was a bug placement and it brings to the black taxt also, no problem is better abore, you are right

this is the problem
![Capture](https://user-images.githubusercontent.com/13486351/59381320-65bdf900-8d5b-11e9-8529-c1b61ac047a2.PNG)

but if i change theme it goes normal
![Capture2](https://user-images.githubusercontent.com/13486351/59381321-65bdf900-8d5b-11e9-85f3-890f12e8f1d1.PNG)
but returns black after

**Comment by Almenon** [comment]
What themes are you switching to/from? Does this happen with all themes?

The only CSS I have for switching colors is for the error and variable output, the print output should not be changing colors like that. This might be a bug with VSCode.

**Comment by ilnerdchuck** [comment]
This appens with all themes, I think is a vscode related problem. Today I will try a full reinstall of vs code and try

**Comment by ilnerdchuck** [comment]
Ok reinstalled all and it works just perfect
