### ISSUE TITLE
Help wanted regarding expanding class objects in output

### ISSUE THREAD

**Issue by securisec** [Almenon/AREPL-vscode#260]
Is there a way to expand the various class variables using arepl? For example, if i run `sh.ls()`, it will output

```
-{
    a: -{
        py/object: "sh.RunningCommand",
        py/newargs: +{1 items},
        py/iterator: +[37 items]
    },
    sh: -{
        py/repr: "sh/sh"
    }
}
```

What i would like to have in this output is `py/iterator` to be expanded and not just show `+[37 items]`

**Comment by Almenon** [comment]
I have a open issue for remembering expanded variables (see https://github.com/Almenon/AREPL-vscode/issues/75) but unfortunately I likely won't have time to do it anytime soon.  In the meantime you can assign to a variable to see the values you want. For example, 

```python
ls_result = sh.ls()
items = [item for item in ls_result]
```

If you don't want to have the second line of code run each time you can move it to the #$end section, like so:

```python
ls_result = sh.ls()

#$end
items = [item for item in ls_result]
```

Code after #$end is not run on each change and can be run manually with control-enter.

I see that you closed the issue - how did you solve your problem?

**Comment by securisec** [comment]
Thanks @Almenon ! thats a great suggestion. I closed the issue for two reason..
- I realized that i can click on the iterators and others to expand the output
- I also didnt ask my question correctly. What would be really awesome is if there was a way to dump all the class attributes in arepl without me using something like
```
attributes = [attr for attr in dir(a) 
              if not attr.startswith('__')]
```
Would be really cool to inspect a class like that in arepl. Maybe a feature request?

**Comment by Almenon** [comment]
I actually had that feature in the last version of arepl - you could do control-enter to output the attributes.  I didn't do it in this version because intellisense should show you the attributes.  But in practice the python extension is pretty buggy and sometimes the intellisense doesn't work, so I suppose that feature would still be useful.  I'll look into adding it back in :)

**Comment by Almenon** [comment]
Alternatively, maybe I can change jsonpickle to show the attributes. [Jsonpickle](https://github.com/jsonpickle/jsonpickle) is the library I use for converting the variables to JSON for sending to frontend. Would be harder to implement but would improve the variable display and reduce the need for [custom handlers](https://github.com/Almenon/AREPL-backend/blob/eb85270c562ed9fd07b201261975f685ba1a8e24/python/custom_handlers.py).

**Comment by securisec** [comment]
That would be awesome! Just for completions sake, make you can define an attribute for `arepl` so that attributes with long values can be truncated by default, but expanded optionally with something like `from arepl import expand; expand = True`?

**Comment by Almenon** [comment]
Long attribute values (lists and such) are already truncated by default because they are nested two layers deep - you can control default expansion level with arepl.Show_to_level setting.
