### ISSUE TITLE
PATH ENOENT

### ISSUE THREAD

**Issue by Move2win** [Almenon/AREPL-vscode#264]
Windows 8.1 64bit
Python 3.7 64bit & 3.6 64bit (both couldn't be recognized by extension, the same error below)

```
Error in the AREPL extension!
Error running python with command: C:\Users\0.0\AppData\Local\Programs\Python\Python37 -u c:\Users\0.0\.vscode\extensions\almenon.arepl-1.0.15\node_modules\arepl-backend\python\pythonEvaluator.py
Error: spawn C:\Users\0.0\AppData\Local\Programs\Python\Python37 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Are you sure you have installed python 3 and it is in your PATH?
            You can download python here: https://www.python.org/downloads/

```

I'm pretty sure that I have installed python3.7.3 in the path C:\Users\0.0\AppData\Local\Programs\Python\Python37

![屏幕截图(583)](https://user-images.githubusercontent.com/45490638/60753046-0e304780-a000-11e9-928b-0128b4d4970c.png)
![屏幕截图(584)](https://user-images.githubusercontent.com/45490638/60753047-0ec8de00-a000-11e9-9fd1-65464de33701.png)
[exthost.log](https://github.com/Almenon/AREPL-vscode/files/3364498/exthost.log)

**Comment by Almenon** [comment]
Thanks for reporting the error - what values do you have set in arepl.pythonpath and python.pythonpath?  What happens when you try doing the same command in the command line?

**Comment by Almenon** [comment]
You can try setting arepl.pythonpath to "python" (without the quotes) and seeing if that fixes it

**Comment by Move2win** [comment]
> Thanks for reporting the error - what values do you have set in arepl.pythonpath and python.pythonpath? What happens when you try doing the same command in the command line?

"python.pythonPath": "C:\\Users\\0.0\\AppData\\Local\\Programs\\Python\\Python37\\python.exe",
"AREPL.pythonPath": "python",

Code work well in debug console terminal (after press F5)



> You can try setting arepl.pythonpath to "python" (without the quotes) and seeing if that fixes it

After set arepl.pythonpath to python, the problem still happened
There is a path "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\..." in Print Output, but I didn't set that path in settings.json (I don't know why this path show in output)

```
Error in the AREPL extension!
Error running python with command: C:\Users\0.0\AppData\Local\Programs\Python\Python37 -u C:\Users\0.0\.vscode\extensions\almenon.arepl-1.0.15\node_modules\arepl-backend\python\pythonEvaluator.py
Error: spawn C:\Users\0.0\AppData\Local\Programs\Python\Python37 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Are you sure you have installed python 3 and it is in your PATH?
            You can download python here: https://www.python.org/downloads/

Print Output:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\core\overrides.py", line 9, in <module>
    from numpy.core._multiarray_umath import add_docstring, ndarray
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\0.0\.vscode\extensions\almenon.arepl-1.0.15\node_modules\arepl-backend\python\pythonEvaluator.py", line 102, in <module>
    import jsonpickle.ext.numpy as jsonpickle_numpy
  File "C:\Users\0.0\.vscode\extensions\almenon.arepl-1.0.15\node_modules\arepl-backend\python\jsonpickle\ext\numpy.py", line 8, in <module>
    import numpy as np
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by Almenon** [comment]
Ah, a numpy error. That should be fixed with the new release. I'll let you know when it's out

**Comment by Move2win** [comment]
> Ah, a numpy error. That should be fixed with the new release. I'll let you know when it's out

Okay, thanks

**Comment by Almenon** [comment]
New release is out, can you try again please? Note that if you try importing numpy you will still get the error but arepl should work for other libraries.

**Comment by Move2win** [comment]
> New release (1.0.16) is out, can you upgrade and try again please? Note that if you try importing numpy you will still get the error but arepl should work for other libraries.

It works now, successful showing results.

By the way, I want to ask why there doesn't have the interactive mode (the one could show the code running process step-by-step), there is only have output results now.

**Comment by Almenon** [comment]
Glad it works!

There is no step by step mode because vscode doesn't have a good API for that.  Also because a step by step mode would be similar to a debugger which vscode already has.

**Comment by Move2win** [comment]
> Glad it works!
> 
> There is no step by step mode because vscode doesn't have a good API for that. Also because a step by step mode would be similar to a debugger which vscode already has.

Thanks a lot, but I really need that step-by-step mode to view some other people's code.
So could you tell me which one is the last previous version that hasn't remove step-by-step mode?
Maybe v1.0.11 or subsequent version (I know the extension have that function before and I'm a really big fan on that)

**Comment by Almenon** [comment]
AREPL has never had step-by-step mode. I think you're getting mixed up with the debugging option offered by [vscode's official python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python).

**Comment by Almenon** [comment]
https://i.imgur.com/3KpVso4.png

**Comment by Move2win** [comment]
> https://i.imgur.com/3KpVso4.png

I'm sorry, I finally find out that I mixed up this extension with Python Preview extension.
And thank you, case closed!  ^_^

![屏幕截图(587)](https://user-images.githubusercontent.com/45490638/61180651-4b25bb00-a64c-11e9-9a52-c8c11ed45dc8.png)

**Comment by MisterAwesome23** [comment]
Oh thanks for this.

I was having trouble setting "arepl.pythonpath" for VSCode.

Turn out we can simply navigate to VSCode>Settings> "search for arepl.pythonpath"

It then highlights the config section of arepl where I simply typed "python" and it worked.
Thank you :)

**Comment by Habibu-R-ahman** [comment]
> > https://i.imgur.com/3KpVso4.png
> 
> I'm sorry, I finally find out that I mixed up this extension with Python Preview extension.
> And thank you, case closed! ^_^
> 
> ![屏幕截图(587)](https://user-images.githubusercontent.com/45490638/61180651-4b25bb00-a64c-11e9-9a52-c8c11ed45dc8.png)

Which debugger are you using here?! looks hot!

**Comment by Habibu-R-ahman** [comment]
> Oh thanks for this.
> 
> I was having trouble setting "arepl.pythonpath" for VSCode.
> 
> Turn out we can simply navigate to VSCode>Settings> "search for arepl.pythonpath"
> 
> It then highlights the config section of arepl where I simply typed "python" and it worked.
> Thank you :)

In my case, I need to add python3

**Comment by Almenon** [comment]
@Habibu-R-ahman that's "python preview" - see https://marketplace.visualstudio.com/items?itemName=dongli.python-preview

Note that it's based off of http://pythontutor.com
