### ISSUE TITLE
Some Stuff Won't Work

### ISSUE THREAD

**Issue by Imdaman021** [Almenon/AREPL-vscode#265]
I just installed your extension, AREPL for Visual Studio Code but I've had some problems with it.

Whenever I use the real-time python running, even when running a command as simple as `print("Hello World")` I get `Error: spawn python ENOENT`
![Capture](https://user-images.githubusercontent.com/53170165/61616307-69726300-acab-11e9-9f23-6cb99d5b23f4.JPG)

It says I should check if I have Python 3 and that it's in my PATH, but both of these requirements are definitely met.  I am also using the latest version of Visual Studio Code.

I've looked around the internet and people have seemingly been having the same issue and had it fixed, but none of those solutions seemed to work for me.  I thought that the best way to find a solution would be to get it from you.

**Comment by Almenon** [comment]
Can you try running the command shown in the error text in the command line? What happens?

**Comment by Imdaman021** [comment]
There was just an update for vscode and the text functions seem to work.  Although this is the case, I can't get the turtle to work for some reason.  It does not have the same error message though..  Here is the result of the Turtle code:
![Capture3](https://user-images.githubusercontent.com/53170165/61689296-465ab880-ad6a-11e9-9262-f2dd942ffb48.JPG)
I'm not sure if this is AREPL related or something to do with vscode because it says there is an indentation error, which I'm guessing means that turtle is unrecognised, even though I imported it.  You said on Reddit that turtle is supposed to work.
![Capture](https://user-images.githubusercontent.com/53170165/61688110-7bb1d700-ad67-11e9-898e-51963c59fc49.JPG)

Inputs also don't work.  I'm not sure if this is meant to be the case or not, being a real-time scratchpad.  This is what I get when I try to do an input:
![Capture2](https://user-images.githubusercontent.com/53170165/61688615-d435a400-ad68-11e9-8206-5bc6406bebf9.JPG)
It doesn't look like an error, but I don't really understand what it means, and I'd like to know more about it, or if inputs should actually work in the first place.

**Comment by Almenon** [comment]
In regards to turtle, you have a indent in your code.  In python indents matter.  A bad indent will result in a syntax error. 

http://www.peachpit.com/articles/article.aspx?p=1312792&seqNum=3

For input you have to assign your input to standard_input and then you can get it via input(), like so:
```python
standard_input = "hello world"
print(input())
```

**Comment by Imdaman021** [comment]
Ok, thanks!  I just accidentally tabbed the turtle commands.  And for the input, in one of your videos I saw you using inputs with the AREPL app.  So I'm guessing this doesn't work in the vscode version.  Do you know if it's possible to add-in or if you're planning on adding it in the future

**Comment by Imdaman021** [comment]
Ok thanks a lot!
