### ISSUE TITLE
Handling Command line arguments (argv[])

### ISSUE THREAD

**Issue by LightCC** [Almenon/AREPL-vscode#275]
I don't see any issues or enhancements for this, but maybe I missed it - is there a way to setup sys.argv[] for command-line inputs in AREPL?  If not, I would think it shouldn't be too hard:

1. Maybe just reuse the input / stdin functionality
2. Or possibly just add argv as a special comment (e.g. #$argv = ['item1', 'item2'])

Thanks for the extension!

**Comment by Almenon** [comment]
Unlike input it's possible to directly assign values to arguments, so custom code for that is not needed:

```python
import sys
sys.argv = ['hey', 'ho']
print(sys.argv) # ['hey', 'ho']
```

I like that you're thinking of ways to improve arepl though, thanks for the idea :)
