### ISSUE TITLE
Showing lambda-functions in Variables section.

### ISSUE THREAD

**Issue by NoamLoewenstern** [Almenon/AREPL-vscode#296]
Seems that the lambda functions are not recognize at all.
Using VSCode (python):
This is the code I am using:

```python
var = 1
def func():
    print('temp_data')
l = lambda: print('some_data')
d = {
    'func': func,
    'lambda_func': l,
}
print(f'func: {type(func)}')
print(f'l: {type(l)}')
```

And the result windows is:

![image](https://user-images.githubusercontent.com/6962980/74051976-b3b9f800-49e1-11ea-91a4-1db944011f0f.png)

**Comment by Almenon** [comment]
AREPL specifically filters out any functions from the variable view. I didn't think anyone would want to see them, guess I was wrong 😬. I need to refactor the backend to take in settings (see https://github.com/Almenon/AREPL-backend/issues/61). Once that is done I can add in a setting to customize what is filtered out.

**Comment by Almenon** [comment]
Done with release 1.0.21

Changelog:

🚀 Sped up backend when pickling primitives

🚀 defaultFilterVars setting added. You can use it to filter out vars of certain types from displaying in the variable view. You can also set a arepl_filter variable in arepl to play around with it in real-time. `arepl_filter=['foo']`

🚀 defaultFilterTypes setting added. You can use it to filter out vars of certain types from displaying in the variable view. You can also set a arepl_filter_type variable in arepl to play around with it in real-time. `arepl_filter_type=["<class 'str'>"]`

🚀 You can now define a arepl_filter_function variable you can use to totally customize the variables appearing in view

🐛 Fixed arepl_store var not working

🐛 [Fixed a TypeError with pandas thanks to David Aguilar](https://github.com/Almenon/AREPL-backend/issues/104)

🔧 Added showNameErrors and showSyntaxErrors settings you can use to not show those errors if they annoy you

🔧 Python 3.4 is no longer supported

**Comment by Almenon** [comment]
You can show functions by adding this to your settings:

```
    "AREPL.defaultFilterTypes": [
        "<class 'module'>",
    ]
```
