### ISSUE TITLE
Feature Request : hide function name of special type in "Variables"

### ISSUE THREAD

**Issue by ok97465** [Almenon/AREPL-vscode#298]
Thank you for you great works.

I would like to have the ability to hide the name of the function of special type in "Variables."

If I import the function below, the function name is specified in the variable window.
```python
from numpy import (array, zeros, arange, conj, deg2rad, rad2deg, conj, exp,
                   sqrt)
from scipy.special import sindg, cosdg, tandg
from numpy import (cos, sin, tan, arcsin, arccos, arctan)
from numpy.random import randn, standard_normal, randint, choice, uniform
```

![스크린샷, 2020-02-09 19-42-08](https://user-images.githubusercontent.com/22970578/74100602-49858c80-4b74-11ea-9cca-ac99cb56a5dd.png)

I am using APERL(1.0.20), python(3.7.4), windows10.

Thank you again. :+1:

**Comment by Almenon** [comment]
I'll look into this - in the meantime you can use the special var `arepl_filter` as a (less than ideal) temporary solution. It will filter out all the variables specified from the display.

```python
from numpy import (array, zeros, arange, conj, deg2rad, rad2deg, exp, sqrt)
from numpy import (cos, sin, tan, arcsin, arccos, arctan)
from numpy.random import randn, standard_normal, randint, choice, uniform

arepl_filter = ["array", "zeros", "arange", "conj", "deg2rad", "rad2deg", "exp", "sqrt", "cos", "sin", "tan", "arcsin", "arccos", "arctan", "randn", "standard_normal", "randint", "choice", "uniform"]

you_should_only_see_this_variable_now = "hello world"
```

**Comment by ok97465** [comment]
Thanks for the quick response.

My workaround to this problem is below.

[Almenon/AREPL-backend/pickler.py](https://github.com/Almenon/AREPL-backend/blob/master/python/pickler.py)
```python
type_filter = ["<class 'module'>", "<class 'function'>",
               "<class 'builtin_function_or_method'>", "<class 'numpy.ufunc'>"]


def pickle_user_vars(userVars):

    custom_filter = userVars.get('arepl_filter', [])

    # filter out non-user vars, no point in showing them
    userVariables = {
        k: v
        for k, v in userVars.items()
        if str(type(v)) not in type_filter
        and k not in specialVars + ["__builtins__"]
        and k not in custom_filter
    }
```

**Comment by Almenon** [comment]
I just added the ability to filter custom types in the backend :) 

Once I do a new release you should be able to use a new variable `arepl_filter_type` to filter out types. I'll also add in a GUI setting so you don't have to write up the type filters each time.

As a bonus I also created a super-powerful `arepl_filter_function`. userVariables is passed into it and you are free to do whatever you want with it before returning it 🚀

**Comment by ok97465** [comment]
I can't wait to use the new AREPL. Thank you very much. :+1: :

**Comment by Almenon** [comment]
Done with release 1.0.21

Changelog:

🚀 Sped up backend when pickling primitives

🚀 defaultFilterVars setting added. You can use it to filter out vars of certain types from displaying in the variable view. You can also set a arepl_filter variable in arepl to play around with it in real-time. `arepl_filter=['foo']`

🚀 defaultFilterTypes setting added. You can use it to filter out vars of certain types from displaying in the variable view. You can also set a arepl_filter_type variable in arepl to play around with it in real-time. `arepl_filter_type=["<class 'str'>"]`

🚀 You can now define a arepl_filter_function variable you can use to totally customize the variables appearing in view

🐛 Fixed arepl_store var not working

🐛 [Fixed a TypeError with pandas thanks to David Aguilar](https://github.com/Almenon/AREPL-backend/issues/104)

🔧 Added showNameErrors and showSyntaxErrors settings you can use to not show those errors if they annoy you

🔧 Python 3.4 is no longer supported
