### ISSUE TITLE
AREPL does not use folder-level settings

### ISSUE THREAD

**Issue by koumakpet** [Almenon/AREPL-vscode#300]
I'm running vscode on Linux (Ubuntu bionic) and when I installed AREPL extension, it gives this error:
```
Error in the AREPL extension!
Error running python with command: C:\Python38-32\python.exe -u /home/koumakpet/.vscode/extensions/almenon.arepl-1.0.20/node_modules/arepl-backend/python/python_evaluator.py
Error: spawn C:\Python38-32\python.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

Are you sure you have installed python 3 and it is in your PATH?
            You can download python here: https://www.python.org/downloads/
```
it seems as if it searched windows path for python instead of the linux one
My python is under: **/usr/bin/python3**

Log from vscode:
```
[2020-02-10 12:52:14.348] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/koumakpet/.vscode/extensions/almenon.arepl-1.0.20/out/src/extension
[2020-02-10 12:52:14.806] [exthost] [info] eager extensions activated
[2020-02-10 12:52:15.961] [exthost] [error] Activating extension almenon.arepl failed due to an error:
[2020-02-10 12:52:15.962] [exthost] [error] Error: Command failed: "C:\Python38-32\python.exe" -m site --user-site
/bin/sh: 1: C:\Python38-32\python.exe: not found

	at checkExecSyncError (child_process.js:629:11)
	at Object.execSync (child_process.js:665:15)
	at Object.<anonymous> (electron/js2c/asar.js:744:23)
	at Object.execSync (electron/js2c/asar.js:744:23)
	at getsitePackagePath (/home/koumakpet/.vscode/extensions/almenon.arepl-1.0.20/out/src/registerAreplDump.js:31:28)
	at Object.registerAreplDump (/home/koumakpet/.vscode/extensions/almenon.arepl-1.0.20/out/src/registerAreplDump.js:11:29)
	at activate (/home/koumakpet/.vscode/extensions/almenon.arepl-1.0.20/out/src/extension.js:49:25)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:710:141)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:709:810)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:708:960
	at async Promise.all (index 0)
```

I should mention that I'm dual booting Windows and Ubuntu, if that is important.

**Comment by koumakpet** [comment]
I managed to fix this by setting AREPL.pythonPath ="/usr/bin.python3", but I still think that this should be the default path for Linux.

**Comment by Almenon** [comment]
Arepl doesnt have "C:\Python38-32\python.exe" hardcoded anywhere - I'm guessing it came from the python.pythonpath setting. Arepl uses that setting if the arepl.pythonpath setting is not specified.

**Comment by Almenon** [comment]
If python.pythonpath is empty then arepl uses `python3` by default on linux

**Comment by koumakpet** [comment]
Oh, now I get it, I synced my settings.json for vscode from windows and I haven't updated the python path there. I haven't noticed that. Thanks for your help.

**Comment by koumakpet** [comment]
But I would still like to mention that my `python.pythonPath` setting was set in **PROJECT/.vscode/settings.json**. So I think AREPL should take pythonPath from there as vscode does, only if it isn't there it should fall back to the default settings.

**Comment by Almenon** [comment]
> Thanks for your help.

Welcome :)

> But I would still like to mention that my python.pythonPath setting was set in PROJECT/.vscode/settings.json. So I think AREPL should take pythonPath from the project settings as vscode does, only if it isn't there it should fall back to the main user settings (than to default).

sorry, I don't understand. How is that different than the current behavior? Can you provide a example?

**Comment by koumakpet** [comment]
Well in vscode there are basically 3 files for settings: default srttings, global user settings and project specific settings (for every workspace, there can be .vscode directory in which there is file settings.json).
In my global user settings I had the wrong path set, but in project specific settings, I had python path set to /usr/bin/python3, which is the correct path, but AREPL seems to take the path from global user settings and ignore the project secific settings.

**Comment by sephross** [comment]
Ran into the same issue, using wsl and venv. Fixed by setting AREPL python path to ${workspaceFolder}/bin/python3.

Agree path should be relative to the workspace/project.

Thanks,

**Comment by koumakpet** [comment]
No problem, thanks for fixing the issue so fast.

**Comment by Almenon** [comment]
@koumakpet arepl does use project settings over user settings. I just tested it - when I typed in nonsense into python.pythonpath for the project settings arepl got a error. Also when I specified a path to python3.6 in project settings and had 3.7 in user settings arepl used 3.6.

I'm guessing you changed the python path by clicking on the version selector in the bottom bar of vscode or running `python: select interpreter` - updating the path that way does not actually update the settings so in that case arepl might be using a different interpreter.

I'm not sure where the python ext stores the python path when it doesn't update the settings unfortunately 🤔

**Comment by Almenon** [comment]
Actually, it turns out the python ext does update the settings - but specifically it only updates the folder-level setting. AREPL doesn't get the folder-level settings for some reason 😬 I'll reopen this as a bug.

**Comment by Almenon** [comment]
I looked into this further and was frustrated to find out that this might be a vscode bug - I can see the folder level setting, but when I inspect the setting while debugging it shows up as undefined! 😱

**Comment by Almenon** [comment]
I opened https://github.com/microsoft/vscode/issues/94241

**Comment by Almenon** [comment]
This should be fixed next release :D

**Comment by Almenon** [comment]
@koumakpet @sephross version 1.0.23 of arepl should now correctly use currently configured interpreter for python extension if arepl.pythonPath is not set - once you update can you test if it is working please?
