### ISSUE TITLE
Internal Arepl error: [ERR_STREAM_DESTROYED]

### ISSUE THREAD

**Issue by lemirser** [Almenon/AREPL-vscode#309]
Hi, I'm encountering an _**internal arepl error**_ when I'm running AREPL.

I'm just printing a sample string with python3.7
`print('test')`

**AREPL OUTPUT**
```
internal arepl error: Error stack: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at PythonShell.send (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\node_modules\python-shell\index.js:285:20)
	at PythonEvaluator.execCode (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\node_modules\arepl-backend\index.js:62:22)
	at ToAREPLLogic.onUserInput (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\out\src\toAREPLLogic.js:79:34)
	at PreviewManager.onAnyDocChange (c:\Users\anon\.vscode\extensions\almenon.arepl-1.0.21\out\src\PreviewManager.js:270:51)
	at listOnTimeout (internal/timers.js:533:17)
	at processTimers (internal/timers.js:475:7)
```

I'm using Windows 10 64-bit and Python version 3.7.0.

**Comment by Almenon** [comment]
I'm guessing arepl is using a outdated version of python. What do you have set for python.pythonpath and arepl.pythonpath?

**Comment by lemirser** [comment]
I didn't declare any setting value for python.pythonpath and arepl.pythonpath. Does it have any impact if I'm also using venv?

**Comment by Almenon** [comment]
Yes. Arepl does not automatically recognize virtual environments. It tries the following in order:
1.Arepl.pythonpath
2. Python.pythonpath
3. Py (or python3 on Mac)

Is python 3.7 your virtual environment? What do you get if you execute `py` in the command line without activating the virtual environment?

**Comment by lemirser** [comment]
I can execute the `py` in the command line without activating the virtual environment. I followed the steps here [Option 2: Activate the Virtual Environment from your Terminal/Command Window and then launch VS Code](https://donjayamanne.github.io/pythonVSCodeDocs/docs/python-path/) and AREPL runs without any issue.

> 1. Ensure none of the Python paths are configured in the settings.json file (leave them to their defaults).
> 2. Open your terminal (command) window and activate the relevant Python environment
> 3. Close all instances of VS Code
> 4. Next, launch VS Code from that same terminal (command window) session

There might be a problem with my vscode settings but it works now. Thank you for your help.

**Comment by Almenon** [comment]
I just managed to reproduce the error! :D 

It happens to me when I have `arepl.pythonpath` set to `python3`. When I execute `python3` in the command line windows thinks I don't have python installed and brings up the windows app store with the python installation page. AREPL doesn't expect that and throws an error.

I can add in code to handle that situation and give a more user friendly error message if that happens :)

**Comment by Almenon** [comment]
Next release AREPL will show the following error message if it tries to launch python and microsoft redirects to the microsoft store:

https://i.imgur.com/O2JInjg.png
