### ISSUE TITLE
code works fine when run, but sometimes, it still shows some errors in arepl instead of showing some other useful information like it usually does.

### ISSUE THREAD

**Issue by Vishwasrr** [Almenon/AREPL-vscode#313]
Thanks for reporting an issue! People like you help me make AREPL better.

There are no complicated reporting guidelines here, but the more info, the better!

Things like operating system, python version (python --version from terminal) are helpful.

If you want to be REALLY helpful you can run the VSCode command "Developer: Open Log File...", choose Extension Host, and copy the file here. Posting the python code you put in AREPL could also be helpful.

**Comment by Almenon** [comment]
What errors does it show?

**Comment by Vishwasrr** [comment]
I wish I had a photo. I'll send it the next time I encounter something
similar.

**Comment by Almenon** [comment]
Closing this issue for now, if you run into a problem comment here and I can reopen it :)
