### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by ModarYaghi** [Almenon/AREPL-vscode#326]
AREPL-vscode presents the output of multiple cases beside each other:
for example:
def func(x,y):
      if x>y:
            return "Yes"
      else:
             return "No"
print(func(5,3))
print(func(9,7))
AREPL output is:  YesYes

**Comment by Almenon** [comment]
I'm not able to reproduce the bug w/ python 3.6.4 or python 3.7.1. Can you send me a picture please? What version of python are you using?

**Comment by Almenon** [comment]
No response in over two weeks, closing. I can reopen if there's a response.
