### ISSUE TITLE
list and other multi-members

### ISSUE THREAD

**Issue by mehrshaad** [Almenon/AREPL-vscode#333]
hi, Can I see list and other multi-member variables in a single line? please help

**Comment by Almenon** [comment]
AREPL does not support the ability to see the contents of a list in a single line. You can click the "-" right next to the variable name to collapse the view into one line, but then it will just show you the number of items in the list, which may or may not be acceptable for your situation.

```
-{
    x: +[1000 items]
}
```

Does that help?

**Comment by mehrshaad** [comment]
> AREPL does not support the ability to see the contents of a list in a single line. You can click the "-" right next to the variable name to collapse the view into one line, but then it will just show you the number of items in the list, which may or may not be acceptable for your situation.
> 
> ```
> -{
>     x: +[1000 items]
> }
> ```
> 
> Does that help?

yeah, it's better than nothing I guess. thanks for the fast respond
