### ISSUE TITLE
arepl_python_evaluator.py", line 44     userError: str,

### ISSUE THREAD

**Issue by yashk01** [Almenon/AREPL-vscode#343]
File "/home/yash/.vscode/extensions/almenon.arepl-1.0.24/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 44
    userError: str,
             ^
SyntaxError: invalid syntax
Variables:

**Comment by Almenon** [comment]
Arepl doesn't work with python 2. You need to configure the pythonpath to use `python3`.

**Comment by Almenon** [comment]
No response - closing. Hopefully that helped.

**Comment by pmventura** [comment]
@Almenon I'm also having the same issue. Looks like because of the python2 but I'm already using python3 using **pyenv** to manage my python versions. I have also cheked my vscode interpreter and it's using 3.7.9 (also from pyenv).

**Comment by caleb15** [comment]
Darn. Probably because the python extension changed how they set the path.trt setting arepl.pythonpath instead

**Comment by pmventura** [comment]
@caleb15  It works after setting the **arepl.pythonpath** to python3. 

<img width="977" alt="arepl-pythonpath-settings" src="https://user-images.githubusercontent.com/4361782/97802825-11cdf000-1c81-11eb-853f-6c8d120f904d.png">

**Comment by caleb15** [comment]
Sweet. Let me know if you have any more questions or feedback

**Comment by pmventura** [comment]
@caleb15 Surely! Thank you so much
