### ISSUE TITLE
Cannot copy the text from the the real-time output pane

### ISSUE THREAD

**Issue by whlinaa** [Almenon/AREPL-vscode#346]
**Describe the bug**
Cannot copy the text from the the REPL pane

Can you please tell me whether it's a bug or a feature that does not exist so far? Thanks.

**Comment by Almenon** [comment]
It's a bug. That's _really_ weird behavior. It might be a internal vscode issue - I opened https://github.com/microsoft/vscode/issues/103325

**Comment by whlinaa** [comment]
Thank you very much for your kind help. I absolutely love your extension, and that is why I switched from Sublime to VS code. A big thank you for creating such an amazing thing!

Looking forward to the bug fix. Thank you!

**Comment by Almenon** [comment]
Hi @whlinaa, would you be interested in a short interview around your (current or former) usage of AREPL? I'm very curious how people are using it.

**Comment by Almenon** [comment]
Also you should be able to copy text from the output pane now!
