### ISSUE TITLE
getcontext().prec 

### ISSUE THREAD

**Issue by drpepper19** [Almenon/AREPL-vscode#347]
**Describe the bug**
getcontext().prec = 2   #changes precision for the Decimal module to 2 sf
this should only affect later lines of code, i.e. after getcontext() is used
However AREPL takes it into account on earlier lines of code also:

**To Reproduce**
from decimal import Decimal, getcontext
print(Decimal("1.6")**Decimal("1.6"))
getcontext().prec = 2   #changes precision
print(Decimal("1.6")**Decimal("1.6"))

**Expected behavior**
2.121250571097591552299891292
2.1
- that is what appears in terminal when run

However AREPL gives
2.1
2.1
- i.e. getcontext is executed before the first Decimal line

**Screenshots**
![image](https://user-images.githubusercontent.com/68813760/88479986-09ac3900-cf4b-11ea-8de2-b0c66d39bef0.png)

**Other Information (please complete the following information):**
 - OS:Windows7
 - Python Version  3

**Additional context**

**Comment by Almenon** [comment]
Thanks for the reporting the bug! This is indeed a bug.

> getcontext is executed before the first Decimal line

AREPL never changes the order of your code. I try to mess with the code as little as possible. The reason why this is happening is that the precision is somehow not reset between runs. For example:

First run: (default prec)
```
2.121250571097591552299891292
2.1
```

Second run: (has new prec from first run)
```
2.1
2.1
```

As a temporary fix while I integrate the fix into the next release you can open the internal arepl engine file (C:\Users\yourUserHere\.vscode\extensions\almenon.arepl-1.0.24\node_modules\arepl-backend\python\arepl_python_evaluator.py), add `import decimal` to the top, and add `decimal.setcontext(decimal.DefaultContext)` right below `asyncio.set_event_loop(asyncio.new_event_loop())`

**Comment by drpepper19** [comment]
> Thanks for the reporting the bug! This is indeed a bug.
> 
> > getcontext is executed before the first Decimal line
> 
> AREPL never changes the order of your code. I try to mess with the code as little as possible. The reason why this is happening is that the precision is somehow not reset between runs. 

OK - but wouldn't it be simpler for AREPL to show the output from the first run? (and you won't have to reset the prec).

Why are there multiple runs anyway?

**Comment by Almenon** [comment]
AREPL runs every time you make a change to the code. (specifically it waits for you to stop typing and then does a run)

You can adjust `AREPL.delay` to configure how long it waits before it runs the code after you stop typing.

**Comment by Almenon** [comment]
I found out why precision is changing inbetween runs - the problem is that Decimal uses [contextvars](https://docs.python.org/3/library/contextvars.html) to store its context, and the context is not reset inbetween runs. By running arepl code inside its own context I can solve this problem, not just for Decimal but for any other library that uses context!

https://github.com/Almenon/AREPL-backend/pull/135#issuecomment-678810109

**Comment by Almenon** [comment]
If you upgrade arepl to v2 this should be fixed now :)

**Comment by drpepper19** [comment]
great thanks!
