### ISSUE TITLE
NameError: a variable is not defined.

### ISSUE THREAD

**Issue by kriolo-ai** [Almenon/AREPL-vscode#348]
students_period_A = ["Alex", "Briana", "Cheri", "Daniele"]
students_period_B = ["Dora", "Minerva", "Alexa", "Obie"]

for i in students_period_B:
    print(i)

#IF you run this code in Python, the NameError will appear saying that students_period_B are not defined, but this variable are defined, if try run without ARELP he code will run normaly.

**Comment by Almenon** [comment]
If I run the code you provided I get a indentationerror because print is not indented.

If I run the code with print indented it works fine, without error.

**Comment by Almenon** [comment]
No response - closing. Feel free to comment if there's still a issue.
