### ISSUE TITLE
Module not found, and cannot set modules in PYTHONPATH like vscode? 

### ISSUE THREAD

**Issue by crimsonhawk47** [Almenon/AREPL-vscode#349]
I am currently using AREPL on a project with a few other people. 

In order to make this work in vscode, the PYTHONPATH environment variable needs to be specified. This is different from the other python path, that literally points to a python dist. This instead helps vscode recognize what modules are in scope. 

A common setting for Python in vscode settings.json is

    "terminal.integrated.env.osx": {
        "PYTHONPATH": "${workspaceFolder}"
    }

Unfortunately, there doesn't appear to be a parallel to this in AREPL. It's creating issues where simple imports are coming with "module not found" errors. 

A project with the following structure:

```
Project
    /app
        __init__.py
        graphics.py
        logic.py
    /tests
        test_graphics.py
```

Can lead to issues. Logic may have this import: 

```
from app.graphics import render
render(...)
```

This would run fine in vscode with the PYTHONPATH variable set, but AREPL throws a ModuleNotFoundError. Is there no way around this short of changing the import? I am working with multiple people that use this import structure and it's fairly common.

**Comment by Almenon** [comment]
AREPL automatically uses any env vars you have set in your .env file in the root of the workspace. You should be able to fix the issue by putting PYTHONPATH=_yourpath_ into a .env file in the root of your workspace - let me know if that works :)

**Comment by Almenon** [comment]
No response - closing
