### ISSUE TITLE
Can't load AREPL from marketplace

### ISSUE THREAD

**Issue by rafskov** [Almenon/AREPL-vscode#350]
**Describe the bug**
I install AREPL from the vscode marketplace and this stack trace prints out instead of any variables.

**Other Information (please complete the following information):**
 - OS: Windows 10
 - Python Version [e.g. 3.7.2]

![AREPL - main2 py - tagui - Visual Studio Code 8_17_2020 8_48_43 PM (2)](https://user-images.githubusercontent.com/25858030/90468349-33c8c500-e0cb-11ea-8f51-bcb1347c95de.png)

**Comment by Almenon** [comment]
What are the values of `arepl.pythonpath` and `python.pythonpath`? AREPL only works with python 3.5 or greater.

**Comment by rafskov** [comment]
Thanks for the hint. I ended up finding that both settings were not actually set. I ended up pointing to a python distro in the json settings file for arepl and it worked!
