### ISSUE TITLE
Error: spawn python ENOENT

### ISSUE THREAD

**Issue by rrklearn2020** [Almenon/AREPL-vscode#351]
I am using the VS-code and just installed AREPL for pythons with virtualenv, but I am getting the error Error: spawn python ENOENT

Note: I am able to use the virtualevn without AREPL, with Python 3.6, tensorflow, Pandas and Numpy. (ubuntu 18.04 LTS)

Details of the error is shared below.

```
Error in the AREPL extension!
Error running python with command: python -u /home/rr/.vscode/extensions/almenon.arepl-1.0.24/node_modules/arepl-backend/python/arepl_python_evaluator.py
Error: spawn python ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

Are you sure you have installed python 3 and it is in your PATH?
            You can download python here: https://www.python.org/downloads/


```

**Comment by Almenon** [comment]
What are the values of the python.pythonPath and arepl.pythonPath settings?

**Comment by rrklearn2020** [comment]
Thank you for extending the support, I solved it by adding the below lines to the launch.json

{
    "python.pythonPath": "/home/............._venv/bin/python3",
    "code-runner.executorMap": {
        "javascript": "node",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "python": "$pythonPath -u $fullFileName",
        "ruby": "ruby",
        "go": "go run",
        "shellscript": "bash"
    },
    "code-runner.showExecutionMessage": false,
    "code-runner.clearPreviousOutput": true 
}

**Comment by rrklearn2020** [comment]
If there is any better way, please inform
