### ISSUE TITLE
How use Env File and Python Path in vscode ?

### ISSUE THREAD

**Issue by arleyyap** [Almenon/AREPL-vscode#352]
My question can be simple but I'm confused, I'm new using AREPL for python in vscode in windows, I have problems when running it with virtualenvs (I use pipenv). that should be put in the following fields:
```
"AREPL.envFile": "",
"AREPL.pythonPath": ""
```

When I run `pipenv --venv` I get the following:
```
C:\Users\arley\.virtualenvs\backend-1Vs3KOzF
```
and if I run `pipenv --py`:
```
C:\Users\arley\.virtualenvs\backend-1Vs3KOzF\Scripts\python.exe
```
If I run in the console of windows `where python` I get the following:

```
C:\Users\arley\AppData\Local\Programs\Python\Python38-32\python.exe
C:\Users\arley\AppData\Local\Microsoft\WindowsApps\python.exe
```

I have tried a few combinations but nothing works for me:
```
Traceback (most recent call last):
  line 1, in <module>
ModuleNotFoundError: No module named 'flask
```

But if I run: `python app.py` everything works correctly

This is mi settings.json:
```
{
    "AREPL.envFile": "",
    "AREPL.pythonPath": "python",
    "AREPL.pythonOptions": [

        "-u"
    ],
    "AREPL.defaultImports": [

        "from arepl_dump import dump"
    ],
    "AREPL.pyGuiLibraries": [

        "matplotlib",
        "tkinter",
        "kivy",
        "pyforms",
        "PyQt4",
        "PyQt5",
        "wx",
        "pyside",
        "plotly",
        "ggplot",
        "bokeh",
        "ppb",
        "PySimpleGUI",
        "pyglet"
    ]
}
```

**Comment by Almenon** [comment]
Where is flask installed? In your virtualenv or in your python site packages directory? You can do `pip freeze` with your virtualenv python and regular python to see where flask is installed. `pip freeze` shows you all the packages that are installed for that python.

**Comment by Almenon** [comment]
If you installed flask in your virtualenv try setting arepl.pythonPath to `C:\Users\arley\.virtualenvs\backend-1Vs3KOzF\Scripts\python.exe`

**Comment by arleyyap** [comment]
Thank you very much for your response.

I have installed flask in my virtualenv. In my arepl.pythonPath enter `C:\Users\arley\.virtualenvs\backend-1Vs3KOzF\Scripts\python.exe` and it worked correctly.

Thanks for your time and I like the extension AREPL.
