### ISSUE TITLE
make it work on python3

### ISSUE THREAD

**Issue by sixbit** [Almenon/AREPL-vscode#364]

**Comment by caleb15** [comment]
Arepl works with python 3. Try adding python2 to arepl.pythonpath

**Comment by Almenon** [comment]
@NUKOD I just released a new version of AREPL (2.0.1) with a few bug fixes. Does it work there?

**Comment by cpuwar** [comment]
I have to add 'python3' in arepl.pythonpath. I use AREPL (2.0.1).

**Comment by Almenon** [comment]
Glad that fixed the issue! 

On a unrelated note, would you be interested in a short interview around your (current or former) usage of AREPL? I'm very curious how people are using it.
