### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by londonreturns** [Almenon/AREPL-vscode#370]
File "c:\Users\Dell\.vscode\extensions\almenon.arepl-2.0.1\node_modules\arepl-backend\python\arepl_python_evaluator.py", line 117
    userError: str,
                  ^(the arrow points to colon)
SyntaxError: invalid syntax

**Comment by Almenon** [comment]
That error means you're using it out of date python version. You need to
use Python 3.7 or above. You might need to specify it in arepl.pythonpath
