### ISSUE TITLE
matplotlib.pyplot not working

### ISSUE THREAD

**Issue by justinkhant** [Almenon/AREPL-vscode#372]
**Plot file didn't terminate**
only force quit is available for me

**Comment by Almenon** [comment]
What code did you use?

**Comment by justinkhant** [comment]
plt.plot(np.array([[1,1,1,1],[0,0,0,0]]))
plt.show()
print("helloworld")

**Comment by Almenon** [comment]
Clicking on the "x" in the top right of the plot window works for me. What do you mean by "force quit"? How is that different from regular quit?

**Comment by justinkhant** [comment]
<img width="1280" alt="Screen Shot 2021-01-12 at 11 24 02 AM" src="https://user-images.githubusercontent.com/56903102/104271509-7c917800-54c9-11eb-8c0d-f89b7a76988f.png">
firstly, I am a beginner and when I found print("something") after matplotlib.pyplot.show() does not work and the plot file is also not responding
. (MacOS)

**Comment by Almenon** [comment]
Weird 🙁. If you're willing to I would try using numpy and matplotlib in vanilla python3.7 or greater instead of anaconda. AREPL doesn't work great with anaconda unfortunately.
