### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by moraKX** [Almenon/AREPL-vscode#373]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Other Information (please complete the following information):**
 - OS: [e.g. Windows10]
 - Python Version [e.g. 22]

**Additional context**

**Comment by caleb15** [comment]
What is the code that caused this bug?

**Comment by Almenon** [comment]
What is the code that caused this bug?

**Comment by Almenon** [comment]
Following up on this.

**Comment by Almenon** [comment]
No response, closing.
