### ISSUE TITLE
AREPL stops refreshing on MacOS

### ISSUE THREAD

**Issue by krisj** [Almenon/AREPL-vscode#376]
**Describe the bug**
Installed the AREPL extension.
trying it out with.py files, seems to work fine until I start to do anything that is not basic variables/lists etc.

**To Reproduce**
1. Install AREPL on VSCode for Mac OS
2. create a test.py
3. add `import requests`
4. add `a = 1`
5. add `r = requests.get('<url>')`
6. start typing in the placeholder to replace with say `https://randomuser.me/api`
7. AREPL crashes with `Traceback (most recent call last):
  line 5, in <module>
  File "/Users/bubble/.pyenv/versions/venv/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/bubble/.pyenv/versions/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/bubble/.pyenv/versions/venv/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/Users/bubble/.pyenv/versions/venv/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/Users/bubble/.pyenv/versions/venv/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/Users/bubble/.pyenv/versions/venv/lib/python3.8/site-packages/requests/models.py", line 393, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https://': No host supplied
`
and doesn't update until I click on the AREPL icon to turn it off/on

**Expected behavior**

expected it to just keep updating through any incomplete lines.

**Other Information (please complete the following information):**
 - OS: Mac OS Mojave 10.14.6
 - Python Version 3.8.7

**Additional context**

I've tried older versions and it is the same situation. With or without venv. Same problem when increasing the delays or changing it to onSave etc.

**Comment by Almenon** [comment]
Sorry about that! Probably because of https://github.com/Almenon/AREPL-vscode/issues/374 - I'm going to release a fix for it eventually but it's taking a while because I'm planning on refactoring the python-shell while I'm at it.

**Comment by Almenon** [comment]
In the meantime you can try downgrading, using regular python debugger, or using wolf.

**Comment by krisj** [comment]
cool, thanks for the suggestion, I had downgraded before but not far enough... downgrading to 1.0.19 worked for me. anything >= 1.0.20 doesn't

**Comment by shakir544** [comment]
@krisj  I am also having the same issue. Will you be able to provide the steps how to downgrade AREPL to 1.0.19 ??? the oldest version is >1.0.19 in this page. https://marketplace.visualstudio.com/items?itemName=almenon.arepl

**Comment by krisj** [comment]
> @krisj I am also having the same issue. Will you be able to provide the steps how to downgrade AREPL to 1.0.19 ??? the oldest version is >1.0.19 in this page. https://marketplace.visualstudio.com/items?itemName=almenon.arepl

@shakir544 
<img width="672" alt="Capto_Capture 2021-03-18_10-29-13_p m" src="https://user-images.githubusercontent.com/590660/111705953-61304980-8839-11eb-9202-8b08f7b06846.png">

**Comment by shakir544** [comment]
Thanks @krisj. Appreciated. I was looking in the wrong place.

**Comment by Almenon** [comment]
This should be working now in AREPL v2.0.2, can you confirm please @shakir544 @krisj ?

**Comment by Almenon** [comment]
oh and side-note if you're using requests I suggest putting the code under a `#$end` comment and evaluating it with control-enter, that way you don't spam the API while you're typing.

https://github.com/Almenon/AREPL-vscode#end

**Comment by shakir544** [comment]
@Almenon yes, its working for me in 2.0.2. Thank You.

**Comment by krisj** [comment]
> This should be working now in AREPL v2.0.2, can you confirm please @shakir544 @krisj ?

yep working here, thank you!

**Comment by Almenon** [comment]
Hi @krisj and @shakir544, would either of you be interested in a short interview around your (current or former) usage of AREPL? I'm very curious how people are using it.
