### ISSUE TITLE
Print output giving the wrong value

### ISSUE THREAD

**Issue by kodakush** [Almenon/AREPL-vscode#377]
**Describe the bug**
When I write a Depth First Search Algorithm the print output seems to be missing a value.

**To Reproduce**
```
def dfs(graph, current_vertex, target_value, visited=None):
    if visited is None:
        visited = []
    visited.append(current_vertex)
    if current_vertex is target_value:
        return visited
    for neighbor in graph[current_vertex]:
        if neighbor not in visited:
            path = dfs(graph, neighbor, target_value, visited)
            if path:
                return path

def bfs(graph, start_vertex, target_value):
    path = [start_vertex]
    vertex_and_path = [start_vertex, path]
    bfs_queue = [vertex_and_path]
    visited = set()
    while bfs_queue:
        current_vertex, path = bfs_queue.pop(0)
        visited.add(current_vertex)
        for neighbor in graph[current_vertex]:
            if neighbor not in visited:      
                if neighbor is target_value:
                    return path  + [neighbor]
                else:
                    bfs_queue.append([neighbor, path + [neighbor]])


some_hazardous_graph = {
    'lava': set(['sharks', 'piranhas']),
    'sharks': set(['piranhas', 'bees']),
    'piranhas': set(['bees']),
    'bees': set(['lasers']),
    'lasers': set([])  
  }   

print("dfs >", dfs(some_hazardous_graph, 'sharks', 'bees'))
print("bfs >", bfs(some_hazardous_graph, 'sharks', 'bees'))
```
**Expected behavior**
via prompt the print output of the dfs function gives me : ['sharks', 'piranhas', 'bees']
with AERPL I'm getting the same output as bfs function : ['sharks', 'bees']

**Screenshots**
![image](https://user-images.githubusercontent.com/63604383/110688607-8204f900-81c0-11eb-8a60-3f4dee3e8dc9.png)

**Other Information (please complete the following information):**
 - OS: Windows10
 - Python Version: 3.9.1

**Additional context**

**Comment by Almenon** [comment]
I wasn't able to reproduce this with windows 10 python 3.9.1, sorry. If you close vscode and restart does the problem still happen?

**Comment by kodakush** [comment]
I tried again today and wasn't also able to reproduce it. sorry for the inconvenience!

**Comment by Almenon** [comment]
No worries :)

By the way would you be interested in a short interview on how you use AREPL (past or present)?
