### ISSUE TITLE
Error: spawn python EACCES

### ISSUE THREAD

**Issue by rjmusic87** [Almenon/AREPL-vscode#378]
**Describe the bug**
AREPL error after first installation in VS Code.

**To Reproduce**
1. VS Code Extensions>Install "AREPL"
2. On any python file, click "eval python in real time (current doc) button

**Expected behavior**
For AREPL to evaluate the open script

**Screenshots**
Error message:
'''
Error in the AREPL extension!
Error running python with command: python -u /home/richardjackson/.vscode-server/extensions/almenon.arepl-2.0.1/node_modules/arepl-backend/python/arepl_python_evaluator.py
Error: spawn python EACCES
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
'''

![arepl-issue-1](https://user-images.githubusercontent.com/5838388/112146646-bbcbfb80-8bd3-11eb-8983-8cf0c3e1f144.png)

**Other Information (please complete the following information):**
 - OS: Windows 10 build 19042 running WSL: Ubuntu-20.04
 - Python Version: Python 3.8.2
- Code Editor: VS Code v 1.54.3

**Comment by rjmusic87** [comment]
Sorted - was an issue to do with Python installations on my machine (somehow I was missing some, and then had to adjust some permissions).

**Comment by rjmusic87** [comment]
This was also helpful: https://github.com/Almenon/AREPL-vscode/issues/293

**Comment by Almenon** [comment]
Hi @jacksorjacksor, you be interested in a short interview around your (current or former) usage of AREPL? I'm very curious how people are using it.

**Comment by jacksorjacksor** [comment]
Hi! Apologies for the late response - happy to answer any Qs, I'm at jacksorjacksor@pm.me (currently not using it but happy to help where I can)
