### ISSUE TITLE
AREPL is showing internal error

### ISSUE THREAD

**Issue by itsabhianant** [Almenon/AREPL-vscode#384]
# My AREPL is showing me this error:

![Screenshot from 2021-04-04 20-17-46](https://user-images.githubusercontent.com/81291713/113512925-ac11c700-9584-11eb-8df2-61cca1eb74d5.png)
 
---
### I recently changed my terminal from bash to zsh:

I installed the AREPL extension 3 days ago. I have VS CODE for both Windows and my UBUNTU system. I have synced both of them. AREPL was working great on both Windows and Ubuntu but it's giving me this error on my UBUNTU machine after I changed my terminal from bash to zsh and installed oh-my-zsh and powerlevel10k theme.

### I also made some changes in settings.json{}:

In order to get a good font on my terminal, I also made changes given below on my setting.json{}:

```javascript
  "terminal.integrated.shell.linux": "/usr/bin/zsh",
  "terminal.integrated.fontFamily": "'SauceCodePro Nerd Font Mono','Source Code Pro'",
  "terminal.integrated.rightClickCopyPaste": true,
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.cursorStyle": "underline",
  "terminal.integrated.cursorBlinking": true
```
---
I don't know what is actually wrong with my AREPL on my UBUNTU machine. Please do help me out because I really want to keep using this powerful extension.

**Comment by Almenon** [comment]
Arepl does not use the terminal so changing it should not matter. Can you try running `whereis python3` and `python3 --version` for me please?

**Comment by Almenon** [comment]
And what is the output of the above commands?

**Comment by itsabhianant** [comment]
I did as per the instructions and got the following outputs:

For:

>whereis python3
```zsh
python3: /usr/bin/python3.8 /usr/bin/python3 /usr/bin/python3.8-config /usr/lib/python3.9 /usr/lib/python3.8 /usr/lib/python3 /etc/python3.8 /etc/python3 /usr/local/lib/python3.8 /usr/include/python3.8 /usr/share/python3 /usr/share/man/man1/python3.1.gz

```
---
And for:

>python3 --version
```zsh
Python 3.8.5
```
---
