### ISSUE TITLE
bottom bar with twitter handle, rate me and gitter links overlays the main window in a way that is messy if theres text behind it.

### ISSUE THREAD

**Issue by ostap-tymchenko** [Almenon/AREPL-vscode#388]
![image](https://user-images.githubusercontent.com/56374185/114971558-8d47e600-9e4a-11eb-8335-09d1a4ad9c1f.png)

**Comment by Almenon** [comment]
That's really weird - not sure what would be causing the issue. What version of vscode are you using? Theme? What about the OS? Is it still like that if you restart vscode?

**Comment by ostap-tymchenko** [comment]
windows 10, latest VScode build, [sublime Monokai theme ](https://github.com/def-SpaceWar/sublime-monokai)

**Comment by Almenon** [comment]
I just checked and you're right, the issue happens with all the themes! 😬 I'm guessing it's because Vscode changed their API so my old css no longer works. I'll fix it in the new release but in the meantime you can set the `arepl.customcss` setting to `#footer{background-color:var(--vscode-editor-background)}` to fix it :)

**Comment by ostap-tymchenko** [comment]
happy i could help! :)

**Comment by Almenon** [comment]
Wow, I thought I released the fix already. Sorry about that. I just released a new version (2.0.3) that fixes this. Also would you be interested in a product interview about your past or current usage of AREPL?

**Comment by ostap-tymchenko** [comment]
sorry for the very very very late reply, didnt see this. AREPL really personally helped me understand what was going on in the backend and it contributed quite a bit to me first learning programming. i wish i could still use it as i now mostly write rust code and python isnt to relevent to what i do. if you still want that interview im down. also how hard would it be to expand this to other langs? as far as i understand AREPL is really just a ``watch`` command with some fancy theming that shows some stats on a file?
