### ISSUE TITLE
Objects are only shown as strings

### ISSUE THREAD

**Issue by Astronaut750** [Almenon/AREPL-vscode#391]
**Describe the bug**
Most objects are shown correctly as Arrays / Lists / Objects. However, for some reason "schoolyears" (SchoolyearList) and "sy" (SchoolyearObject) are only shown as strings. These objects are from the webuntis python library.
Is this a problem on my end?

**Expected behavior**
"schoolyears" should be shown like "departments" as an array.

**Screenshots**
![image](https://user-images.githubusercontent.com/38164738/115672960-5db64380-a34c-11eb-964e-256a1a3efb3a.png)

**Other Information:**
 - OS: Windows 10
 - Python Version 3.9.1

**Comment by Almenon** [comment]
Look in https://github.com/python-webuntis/python-webuntis/blob/51aa2df293f01dcdf2c278386d513dbfc1c2115c/webuntis/objects.py#L499 - SchoolyearList inherits from ListResult, which has a \_\_repr\_\_ method. \_\_repr\_\_ is a special "dunder" (double-underscore) method that controls the representation of the object - see [python docs](https://docs.python.org/3/library/functions.html#repr). 

Normally AREPL uses \_\_getstate\_\_ to represent a method, but the library AREPL uses to pickle variables ([jsonpickle](https://github.com/jsonpickle/jsonpickle)) sometimes tries out different tactics, so for some reason this time it's using the \_\_repr\_\_ method. I would try deleting the repr method and seeing if it goes back to showing data like normal:

`del schoolyears.__class__.__repr__`

You can also try overriding the __repr__ method to customize the output to your liking:

```python
def custom_repr(self):
  return "hello world"
  
schoolyears.__class__.__repr__ = custom_repr
```

**Comment by Almenon** [comment]
Closing, no response. Let me know if you have further questions / feedback
