### ISSUE TITLE
Using Python 3.9.4 and AREPL extension keeps on telling me to use Python 3

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [Almenon/AREPL-vscode#392]
# Issue
I have been using Python 3.9.4 for a while with many extensions. However, AREPL seems to have trouble. It keeps on telling me to use Python 3, which I am already using. I tried evaluating in real doc, current doc, run block code, and all the commands. It all tells me to use Python 3.

# Expectation
I expected it to debug Python and when I change code, debug again. However, it does not seem to be working. It will be really efficient to use this extension. Please look into this problem.

# Programming Environment
I am using Python version 3.9.4 and the latest version of AREPL. I am using Windows10 and VSCode version 1.56.0 (the latest).

# Screenshot of error
![SharedScreenshot](https://user-images.githubusercontent.com/78584173/117276804-36a65880-ae9a-11eb-8c29-54e4e83d6a89.jpg)

**Comment by Almenon** [comment]
What value do you have for python.pythonpath and arepl.pythonpath settings?

**Comment by Almenon** [comment]
No response, closing. @HyunseungLee-Travis note that I released a new version of AREPL (v2.0.3) that automatically uses the interpreter you have set for the python extension, so if you upgrade it may start working.
