### ISSUE TITLE
err code: 1 - userError: str, invalid syntax

### ISSUE THREAD

**Issue by bummings** [Almenon/AREPL-vscode#394]
**Describe the bug**
Hi! I cannot for the life of me figure out why I'm getting this error. I've never been able to get AREPL to run on my system.
Think I have been able to trace this to a Python path issue, though I am lost as to where it is looking. Unless I am missing something current version of Python is not living in `~/usr/local/bin`, if that is where it is looking by default. Same goes for `~/usr/local/sbin`, which is empty.

**To Reproduce**
1. Open Python file
2. Click on the eval in real time button or `shift` + `cmd` + `A`
3. See error in bottom right: `AREPL no longer supports Python 2.7.16.` 

**Expected behavior**
Tab will open up with the error as the screenshot below will show

**Screenshots**
[![Screen-Shot-2021-05-10-at-2-08-17-PM.png](https://i.postimg.cc/ZnZhSkTq/Screen-Shot-2021-05-10-at-2-08-17-PM.png)](https://postimg.cc/wyWrXGRK)

**Other Information (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3
 - Python Version: 3.8.2

**Comment by Almenon** [comment]
Hi Edd! Can you give me the value of `AREPL.pythonPath` and `python.pythonpath` please? 

Can you also execute the below in the terminal please and post the results?
```
where python
python --version
where python3
python3 --version
```

**Comment by bummings** [comment]
Oh wow. That helped me fix it- thank you, Almenon! I had to supply the path for Python3- there was none specified in the settings JSON file. Much appreciated.

**Comment by Almenon** [comment]
Welcome. :) You may still run into https://github.com/Almenon/AREPL-vscode/issues/387 - if so let me know.

**Comment by Almenon** [comment]
Hi @bummings, would you be interested in a short interview around your (current or former) usage of AREPL? I'm very curious how people are using it.
