### ISSUE TITLE
Venv + AREPL

### ISSUE THREAD

**Issue by Hyderman** [Almenon/AREPL-vscode#396]
Hi,

It's not really a bug but i'm new on vscode.
I have the problem of import not found with VENV.
I saw you said that we have to change the path for AREPL to use VENV module but i don't know what way use to automatically use VENV path for AREPL.

I go to settings then Extensions then AREPL configuration i find Env fil and python path.

What could i put to say "use the interpreter which i'm using now" ?

Thanks.

**Comment by Almenon** [comment]
If you don't specify anything for `arepl.pythonpath`, AREPL should use the same python interpreter that you select for the python extension. So for example if you have python 3.6.4 venv selected, [as in this picture](https://i.imgur.com/PahgFAb.png), then AREPL should use that same version. You can change the interpreter by clicking on it.

**Comment by Hyderman** [comment]
Thanks it works perfectly now.

**Comment by Almenon** [comment]
Hi @Hyderman , would you be interested in a short interview around your (current or former) usage of AREPL? I'm very curious how people are using it.
