### ISSUE TITLE
It's stuck on the landing page when i type its not showing the code

### ISSUE THREAD

**Issue by w12yeah** [Almenon/AREPL-vscode#398]
How do i make it work its stuck on the landing page i tried reinstalling and deleting but it still doesnt work

**Comment by w12yeah** [comment]
nvm i reinstalled everything and it worked

**Comment by Almenon** [comment]
Hi @w12yeah, would you be interested in a short interview around your (current or former) usage of AREPL? I'm very curious how people are using it.
