### ISSUE TITLE
AREPL-vscode not working!

### ISSUE THREAD

**Issue by aaryaji** [Almenon/AREPL-vscode#400]
when we click the cat 🙀 button or top-right corner of the window it doesn't respond! doesn't do anything!!

Expected that it should open a side window and show a live preview of code.

 - OS: Windows10
Have Installed Python3.9.5
have env path var set to 
C:\Python39\
C:\Python39\Scripts\
C:\Python39\Lib\site-packages\
C:\Users\om\AppData\Roaming\Python\Python39\Scripts\

vs code extensions  installed
AREPL   v2.0.2
python  v2021.5.842923320
pylance  v2021.5.4
jupyter  v2021.6.832593372

VS Code Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Almenon** [comment]
Hmm 🤔 What about when you press control shift q?

**Comment by aaryaji** [comment]
it reacts nothing!!

**Comment by aaryaji** [comment]
Dear,
i tried hard to resolve it..
but failed..
i'd uninstalled python 3.9.5 and downgraded it to 3.8.10 that's the only solution I found..

Thanks Developers..
You really made a useful extension 
Thanks again.
🕉 🙏

**Comment by Almenon** [comment]
Weird, AREPL should work with python 3.9. 

> You really made a useful extension
Welcome :)
