### ISSUE TITLE
Not working with Pytorch

### ISSUE THREAD

**Issue by ayberkydn** [Almenon/AREPL-vscode#401]
**Describe the bug**

Whenever a file imports pytorch, it produces an error.
```
Traceback (most recent call last):
  line 3, in <module>
  File "/home/ayb/.local/anaconda3/envs/deep-learning/lib/python3.8/site-packages/torch/__init__.py", line 447, in <module>
    from .tensor import Tensor
  File "/home/ayb/.local/anaconda3/envs/deep-learning/lib/python3.8/site-packages/torch/tensor.py", line 13, in <module>
    from torch.overrides import (
  File "/home/ayb/.local/anaconda3/envs/deep-learning/lib/python3.8/site-packages/torch/overrides.py", line 1212, in <module>
    has_torch_function = _add_docstr(
RuntimeError: function '_has_torch_function' already has a docstring
```

**To Reproduce**
Open AREPL with a file imports pytorch with
```
import torch
```

**Screenshots**

![image](https://user-images.githubusercontent.com/23614188/120558426-1bcaf380-c408-11eb-99d8-44437c034e50.png)

**Other Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.4 (conda)
 - PyTorch version: 1.8.1

It actually works for the first time it runs, then produces this error.

**Comment by Almenon** [comment]
Thanks for the report, I was able to reproduce the error with python version 3.6.4 and the following packages:
```
torch==1.8.1+cu102
torchvision==0.9.1+cu102
torchaudio===0.8.1
-f https://download.pytorch.org/whl/torch_stable.html
numpy==1.19.5
```

**Comment by Almenon** [comment]
Unfortunately doesn't look like there's a easy solution to this... the docstring gets added in C code, and I'm not a C expert. See https://github.com/pytorch/pytorch/blob/059a717c9e1e08485f5ef3f13738d1f3e5a33d9e/torch/csrc/Module.cpp

Possibly related: https://github.com/pytorch/pytorch/issues/6998

**Comment by jaideepheer** [comment]
Found a workaround.
Add `torch`, `numpy`, `torchvision` etc. libraries to your `AREPL.pyGuiLibraries` setting in `settings.json`.
Mine looks like this,
```
    "AREPL.pyGuiLibraries": [
        "matplotlib",
        "tkinter",
        "kivy",
        "pyforms",
        "PyQt4",
        "PyQt5",
        "wx",
        "pyside",
        "plotly",
        "ggplot",
        "bokeh",
        "ppb",
        "PySimpleGUI",
        "pyglet",
        "torch",
        "numpy",
        "torchvision"
    ],
```

**Comment by jaideepheer** [comment]
`numpy` still loads twice for some reason.

**Comment by Almenon** [comment]
Good workaround. When the library is in there AREPL starts completely fresh
each time.
