### ISSUE TITLE
Error in the AREPL extension (err code: 1)

### ISSUE THREAD

**Issue by nextlevelwebdesign** [Almenon/AREPL-vscode#402]
**Describe the bug**
AREPL isn't working on my computer and is showing this error:
Error in the AREPL extension!
err code: 1

Print Output:
  File "/Users/jon/.vscode/extensions/almenon.arepl-2.0.2/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 117
    userError: str,
             ^
SyntaxError: invalid syntax
Variables:

I'm on a Mac with this Visual Studio Code:
Version: 1.57.0 (Universal)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z (2 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

<img width="998" alt="Screenshot 2021-06-12 at 10 01 37" src="https://user-images.githubusercontent.com/77211097/121771111-3ff3a680-cb65-11eb-8241-7bfbe3131eab.png">

**Comment by Almenon** [comment]
That you means you're using an older python version. You need at least python 3.6

**Comment by fhumayun** [comment]
Having exactly the same issue in Python 3.8.8
![image](https://user-images.githubusercontent.com/4992990/123527800-71fe2000-d6b0-11eb-9f50-8231634a6f9f.png)

**Comment by Almenon** [comment]
@fhumayun the python in the terminla is 3.8.8, but the python version AREPL is using in your case is different. Try setting `arepl.pythonPath` to `python`, or if that doesn't work, `/usr/bin/python3`
