### ISSUE TITLE
err code: 9009 python is installed and in the path

### ISSUE THREAD

**Issue by fordsi** [Almenon/AREPL-vscode#403]
Hello,

someone nice has time for a beginner?

I have installed: 3.9.5 with a Windows installer.
Python is here: C:\Users\Samsung\AppData\Local\Programs\Python\Python39
I set following as PATH (system variable) C:\Users\Samsung\AppData\Local\Programs\Python\Python39
Before doing so "python --version" gave me an error in CMD, but now it starts accepting python code, but still don't give me python version, instead I have this:

> >>> python --version
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'python' is not defined

Restarted PC, CMD and vscode.

Not an issue with AREPL so I am ok if the thread gets deleted.

**Comment by Almenon** [comment]
I would try doing `echo %PATH%` in the CMD. You can copy and paste that into a text editor and search for `C:\Users\Samsung\AppData\Local\Programs\Python\Python39` to see whether that is actually in your PATH. Once you do that... hmmm.. not really sure what the next steps would be. I could probably help you out real fast over a video call - what timezone are you in? Do you have discord/zoom?

**Comment by fordsi** [comment]
Thanks for the idea with echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;C:\Users\Samsung\AppData\Local\Microsoft\WindowsApps;;
C:\Users\Samsung\AppData\Local\Programs\Microsoft VS Code\bin
 I reopened environment variable and as last line I have: C:\Users\Samsung\AppData\Local\Programs\Python\Python39 Weird that all other entries start with %SystemRoot% but I get following outputfor the path command

Maybe I have the issue because of weird installation path of Python?C:\Users\Samsung\AppData\Local\Programs\Python\Python39

Yes I have discord: fordsi#5656

**Comment by fordsi** [comment]
Hello Almenon,

after another restart AREPL works. I didn't change the environment variable, no idea why AREPL works. Thank you for your time.
