### ISSUE TITLE
err code: 9009  in  python3

### ISSUE THREAD

**Issue by tea-2017** [Almenon/AREPL-vscode#407]
Error in the AREPL extension!
err code: 9009

Are you sure you have installed python 3 and it is in your PATH?
            You can download python here: https://www.python.org/downloads/

**Comment by Almenon** [comment]
I just released a update - if you upgrade AREPL to v2.0.3 it should now automatically use the interpreter you have set in the python extension. Do you have the python extension?

**Comment by Almenon** [comment]
No response - closing
