### ISSUE TITLE
AREPL window from VScode extension does not react.

### ISSUE THREAD

**Issue by CharlieCurious** [Almenon/AREPL-vscode#408]
Nothing is shown on the AREPL window when I type any code. When I press  the AREPL symbol, the window shown, even though it corresponds to the current file, it's just stuck on the startup.

I'm running VScode on Pop_OS and using Python version 3.9.5.
I've installed the extension via almenon.arepl-2.0.2.vsix

![Screenshot from 2021-07-08 11-51-01](https://user-images.githubusercontent.com/67659875/124909926-ea36e080-dfe2-11eb-917c-0a330d2a61cb.png)

**Comment by Almenon** [comment]
Woah, never heard of pop os before. If you open up the developer tools and go to the console are there any errors?

**Comment by CharlieCurious** [comment]
Sorry, @Almenon, I don't know how to open up developer tools....

**Comment by Almenon** [comment]
Ah, that means arepl can't find your python executable. Try adjusting the `arepl.pythonpath` setting. How do you run python in your terminal?

**Comment by CharlieCurious** [comment]
>  How do you run python in your terminal

Just simply by running 
`python3 script.py`

But usually I'm using a venv.

**Comment by Almenon** [comment]
Then to make it work you can either change arepl.pythonpath to `python3` or change it to the path to your venv executable.

**Comment by CharlieCurious** [comment]
That worked! Thanks!
