### ISSUE TITLE
AREPL on Vscode on WSL-Remote unresponsive

### ISSUE THREAD

**Issue by ruperty** [Almenon/AREPL-vscode#413]
**Describe the bug**
I can open the arepl window. But when I make changes in the python file the arepl window doesn't change from the intro text.

**To Reproduce**
1. Open python file
2. Open arepl
3. Make changes in python file
4. Nothing happens in arepl window

**Expected behavior**
Arepl window should show updated results.

**Screenshots**
![image](https://user-images.githubusercontent.com/259477/125617511-09bf0447-b972-4a1c-9c7c-68e9045e4cd4.png)

**Other Information (please complete the following information):**
 - OS: 
 - Windows10/WSL
 - Python Version 
 - 3.7.9 

Any help most appreciated.

**Comment by Almenon** [comment]
How do you run python in your terminal? You can put the same command in `arepl.pythonpath`

**Comment by perceptualrobots** [comment]
@Almenon thanks for your repsonse. Sorry, I don't know what you mean, python is being run by VSCode. What is arepl.pythonpath?

**Comment by Almenon** [comment]
Arepl.pythonpath is a setting in Vscode. If you set it to the path to your python executable AREPL should start working.

**Comment by perceptualrobots** [comment]
Do you mean like this, "arepl.pythonpath":"/home/ruperty/anaconda3/envs/dev37/bin/python", in a settings.json file?

I tried this for the settings.json in the project folder and also for the arepl extension on WSL, but they do not seem to have worked. The arepl window doesn't change from the intro text.

**Comment by Almenon** [comment]
Yep. I'm not sure how well AREPL works with anaconda however. I'm going to be releasing a update to AREPL soon that should help with path issues, I'll let you know when.

**Comment by Almenon** [comment]
I just released the update. AREPL should now automatically use the interpreter you have set in the python extension.

**Comment by perceptualrobots** [comment]
That seemed to do it, thanks.
