### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by income3000** [Almenon/AREPL-vscode#415]
**Describe the bug**

keep getting this error and I'm using python3 version 3.9.6 but its not reading it

![Screen Shot 2021-07-21 at 5 46 21 PM](https://user-images.githubusercontent.com/84121059/126564436-de47fab3-49f7-4eb0-b119-10044b06da29.png)

**Comment by income3000** [comment]
still waiting for a reply

**Comment by Almenon** [comment]
What value do you have for arepl.pythonpath?

**Comment by income3000** [comment]
Where do I find that

**Comment by Almenon** [comment]
In the vscode settings

**Comment by income3000** [comment]
It’s blank

**Comment by Almenon** [comment]
Do you have the python extension? I just released a new version of AREPL that uses the interpreter you have set for the python extension automatically.

**Comment by Almenon** [comment]
Closing - no reply
