### ISSUE TITLE
ARPEL not loading on Vscode

### ISSUE THREAD

**Issue by rhyswells101** [Almenon/AREPL-vscode#417]
I am pretty new to coding. I'm trying to get APREL working but its not loading any ideas on what to do?

![Screenshot 2021-07-24 093003](https://user-images.githubusercontent.com/61824581/126862712-f3be7976-1584-4def-9c99-31a44f727289.png)
]

![Screenshot 2021-07-24 093208](https://user-images.githubusercontent.com/61824581/126862745-a62a2cbe-5a5b-4c6d-9d8e-a550c5b99490.png)

 - OS: [Windows10]
 - Python Version [3.8.8]

**Comment by Password-Classified** [comment]
Have you tried changing some stuff in the code. It should auto-run.

**Comment by rhyswells101** [comment]
![Screenshot 2021-07-24 162418](https://user-images.githubusercontent.com/61824581/126873159-ddb50e82-10aa-48d7-bdd6-bc43d7df5a24.png)

Yeah I'v tried this. I have the feeling its because of the anaconda interpreter ?
C:/Users/RhysL/anaconda3/python.exe

**Comment by rhyswells101** [comment]
I figrued it out, you need to change the ARPEL python path if you are using python.exe in anaconda. 
![Screenshot 2021-07-24 162912](https://user-images.githubusercontent.com/61824581/126873317-cbab3469-e220-4c28-ba38-ec35776d9c9d.png)

![Screenshot 2021-07-24 162857](https://user-images.githubusercontent.com/61824581/126873325-3dc35a73-7bcc-4804-b969-bd5ada32bb2c.png)
