### ISSUE TITLE
Option or command to choose if variables view is expanded or collapsed

### ISSUE THREAD

**Issue by neutralvibes** [Almenon/AREPL-vscode#423]
**Is your feature request related to a problem? Please describe.**
Would be nice to expand the `variables` json manually when I want to see them, but would prefer not have them turned off completely. I can't see an option to default them to open or closed.

**Describe the solution you'd like**
If it doesn't already exist, it may be useful to have a config option to set  a `Default variable state` to `expanded` or `collapsed`. You may not choose to expand manually on every run iteration, but it is less distracting and a single click away.
 
**Describe alternatives you've considered**
As an alternative or perhaps in addition to _above_, a directive or two maybe useful so the state can be switched in a comment line.
~~~python
#$vars-collapse
#$vars-expand
~~~

**Comment by Almenon** [comment]
`AREPL.show_to_level` might do what you want. It controls what nested level is automatically expanded by default. Try playing around with it and let me know what you think. 0 collapses everything and the higher the number the more stuff that is expanded.

**Comment by neutralvibes** [comment]
Thanks for the response and sorry for the delay.  After testing `AREPL.show_to_level` I see this only affects the max depth of iterable variables shown, and not the **default state** of the **view** of variables, being either opened or closed.

**Comment by neutralvibes** [comment]
As an example I would prefer my view after an execution to be like this

> **PrintOutput:**
> Run: True, Show:  True, Completed: whenever, Dinosaurs: died
>  
>
> **Variables:**
> +{16 items}

I could then toggle the variables open if I wanted to examine them.

**Comment by Almenon** [comment]
I might be misunderstanding something here. If you set the max depth to 0 then all the variables will be closed by default.

For example: https://i.imgur.com/xurDLBW.png

**Comment by neutralvibes** [comment]
When I set it to 0 depth I get

> Variables:

It's completely empty, does not show totals or have `+` to expand. Which kind of makes sense, as no depth should mean do not look at anything.

**Comment by neutralvibes** [comment]
### Correction
It appears to be working as intended at the moment. My previous comment was actually what I saw. Restarting vscode may have done the trick. Sorry to have wasted your time and thank you for using it.

**Comment by neutralvibes** [comment]
All good

**Comment by Almenon** [comment]
No worries :) thanks for using arepl! 

By the way, would you be open to a user experience interview? I'm curious what you think of arepl.

**Comment by neutralvibes** [comment]
I must confess I only recently started using it. If that meets your critera I don't mind assisting.

**Comment by Almenon** [comment]
Are you free tomorrow or Monday night for a short interview?
