### ISSUE TITLE
Arepl bugs with relative file paths

### ISSUE THREAD

**Issue by Bittu5134** [Almenon/AREPL-vscode#424]
**Describe the bug**
arepl shows me an error in this script.
```
with open('.\\never have i every\\1.json','r') as file:
    print(file.read())
```
error
```
Traceback (most recent call last):
  line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '.\\never have i every\\1.json'
```
**To Reproduce**
just use the above code 

**Expected behavior**
to print the text of that file

**Screenshots**

![Capture](https://user-images.githubusercontent.com/89441005/150480381-8b87312c-838f-4681-981a-693be79749d9.PNG)

**Other Information (please complete the following information):**
 - OS: Windows 7
 - Python Version 3.8

**Additional context**
the code works in the shell but not with arepl

**Comment by Almenon** [comment]
`1.py` is in the `never have i every` directory. So your code is trying to look for a `never have i every` folder _within_ the `never have i every` folder. A subfolder with that name does not exist, so it raises an error.

**Comment by Bittu5134** [comment]
How to fix it (sorry i didn't understand the issue)

**Comment by Almenon** [comment]
Try changing the argument to the open function until it works. Maybe just '1.json'?

**Comment by Almenon** [comment]
Closing - no response
