### ISSUE TITLE
Error in the AREPL extension! err code: 3221225781

### ISSUE THREAD

**Issue by msakthiganesh** [Almenon/AREPL-vscode#425]
**Describe the bug**

AREPL not working. Get the below-mentioned error.

Error in the AREPL extension!
err code: 3221225781

**To Reproduce**
1. Fresh install of Windows 10/11 (tried on both), Anaconda, and VS Code. 
2. Created anaconda environments, and set the Python interpreter to the anaconda environment created. 
3. Installed AREPL from VS Code Extensions. 
4. Get the error

**Screenshots**
![image](https://user-images.githubusercontent.com/47854670/158029739-f17224a0-5f1b-4ce7-a7ee-8dfb7618dca7.png)

**Other Information (please complete the following information):**
 - OS: Windows 10 & Windows 11
 - Python Version 3.9.7

Thanks!

**Comment by Almenon** [comment]
AREPL doesn't work well with anaconda, unfortunately. I would try using python by itself (ex: installed from [python.org](https://www.python.org/downloads/))

**Comment by msakthiganesh** [comment]
Hi,

Thank you for your response. I have been using AREPL with Anaconda on my other machine running Windows 10. I have also tried using AREPL with different python versions (3.6 onwards, up to 3.9), but it works just fine!

Could you please provide me details on the error code which can help me fix the issue? 

Cheers!

**Comment by Almenon** [comment]
The error code is not generated by AREPL, so I'm not sure what's causing it exactly. I googled and found https://stackoverflow.com/questions/49413443/trouble-debugging-error-with-exit-code-3221225781-missing-libraries-in-windows, but stackoverflow is currently down 😅

**Comment by msakthiganesh** [comment]
Hey @Almenon ,

There was some error with my python setup on my machine. The anaconda environments were not defaulting even after setting environment variables. 

The issue was fixed after installing Python directly from python.org as you had suggested earlier. 

Thanks and Cheers!

**Comment by Almenon** [comment]
Hi @msakthiganesh , glad to hear you fixed your problem. Would you be open to a short customer interview on how you used/use AREPL?
