### ISSUE TITLE
UserWarning: The NumPy module was reloaded (imported a second time)

### ISSUE THREAD

**Issue by chiboreache** [Almenon/AREPL-vscode#427]
**Describe the bug**
`UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.`

**To Reproduce**
`import numpy as np`

**Other Information (please complete the following information):**
 - OS: Arch Linux
 - Python Version 3.10

**Comment by chiboreache** [comment]
possible workaround 

```python
import warnings
warnings.filterwarnings('ignore')
```

**Comment by simonnchong** [comment]
facing the same issue here, it occurs when I import pandas module, other than the solution above, any idea to solve it from setting? So I don't have to import the warning module whenever I wanna use pandas or numpy library

**Comment by Almenon** [comment]
You could add the warning filter code to the `AREPL.defaultImports` setting. That automatically adds code to the start of each new arepl file you open.

Another option is you could add the code directly to the arepl python evaluator backend, although you would have to re-add the code every time AREPL gets an update. Fortunately for you, AREPL does not get updates often.

If you wanted to take the second approach you would need to find the AREPL extension code and then insert the workaround by chiboreache in the `arepl_python_evaluator` file right before with `script_path(os.path.dirname(exec_args.filePath)):`. On my windows machine the AREPL extension code is in `C:\Users\almenon\.vscode\extensions\almenon.arepl-2.0.3\node_modules\arepl-backend\python`.

I suppose I could add a feature to invisibly inject code for the user, but that sounds kinda sketchy from a security perspective.

**Comment by Almenon** [comment]
@chiboreache the warning isn't a bug, because numpy is correct in that there can be subtle bugs when reloading numpy. It's a good thing to be aware of. I'm going to mark this issue as a question.

**Comment by simonnchong** [comment]
@Almenon yeah I used the second approach and now it is solved, thanks for the reply😊
