### ISSUE TITLE
Consider becoming a verified publisher

### ISSUE THREAD

**Issue by isidorn** [Almenon/AREPL-vscode#429]
Hi VS Code PM Here 👋

Consider becoming a verified publisher. More details about this can be found here
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

We would love this to happen, so let us know if we can help somehow from the VS Code side.
Thank you

fyi @chgill-MSFT

**Comment by Almenon** [comment]
I don't have much incentive to do this at the moment - I don't have a
website so I would have to create one and pay for the hosting. Let me know
if you're thinking of making this affect the search rankings.
