### ISSUE TITLE
error on linux

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#43]
command not found when starting the extension.  Reported by a user on facebook.  He switched to windows and it worked so it's probably something specific to linux.

**Comment by Almenon** [comment]
Finally got my VM set up, after some [trial and error](https://www.reddit.com/r/vmware/comments/859b1k/corrupted_view_w_ubuntu_16_on_virtualbox/)

I tried starting AREPL to no success, just as expected.  I opened up the logs:

> Cannot find module './utilities'

How is that possible?  utilities is right there in the file explorer! I see it right there! Utilities!

Oh wait... crap

stupid case sensitivity.

**Comment by Almenon** [comment]
waiittt.... as far as I can tell, utilities has _always_ had lowercase u

Yet in my extension is packaged with a uppercase U... WTF

**Comment by Almenon** [comment]
oh - I found it.  I looked in 

> %USERPROFILE%\.vscode\extensions

and my out folder had uppercase U.  

I went to my local repo - same thing, out folder (compiled TS->JS files) had uppercase U.  

What must have happened is that _at some point in time_ I had a uppercase U for utilities, and when I changed it the change did not make it over to the out folder, since as far as the typescript compiler was concerned utilities was already in existance.

**Comment by alendit** [comment]
The problem seem to persist on AREPL 1.0.0 on linux. Changing the name of `Utilities.js` in out/src/ to `utilities.js` solves it.

**Comment by Almenon** [comment]
@alendit the problem didn't persist - it was fixed.  But apparently the 1.0 release reintroduced it.  I'm not sure how though - I havn't changed the name of utilities or the imported name since.

... Oh wait, I know how.  I published the newest version on a different computer - it must have had the out-of-date "Utilities.js" file in the compiled directory.  I'll nuke that directory next time I use the computer.  

In the meantime, let me publish a new version. Thanks for the report.

**Comment by Almenon** [comment]
I just published the new version - does that fix the problem?

**Comment by Almenon** [comment]
No response from @alendit  - hopefully it fixed it? I do see less errors in the telemetry error log.

Also I submitted a pull request https://github.com/Microsoft/TypeScript/pull/27464 to turn case sensitivity on by default for typescript. This should prevent other extension authors from running into the same issue.
