### ISSUE TITLE
Spam When Infinite Loop

### ISSUE THREAD

**Issue by Im-A-Banana** [Almenon/AREPL-vscode#430]
I have a piece of code where it loops for the user's unput, and AREPL spams "AREPL requires standard_input to be hardcoded, like so: standard_input = 'hello world'; print(input())"

Code:
```
inputs = []
while True:
    temp = input().split(" ")
    if(temp[0] == "0" and temp[1] == "0"):
        break
    inputs.append(temp)
    
for i in range(len(inputs)):
    print(int(inputs[i][0])+int(inputs[i][1]))
```
It should say like infinite loop or something

 - OS: WIndows 11
 - Python Version 3.something

**Additional context**
none boomers

btw sub to my yt https://www.youtube.com/antikbnoob

**Comment by Almenon** [comment]
> It should say like infinite loop or something

Harder than it sounds. Mathematically speaking, detecting a infinite loop in a dynamic program is literally impossible. https://www.youtube.com/watch?v=VyHbd6sx5Po

---


AREPL doesn't have a way of putting in input at runtime. You have to hardcode it in advance, as stated by spammy messages.

For example:
```python
standard_input = ['1 1']
inputs = []
while True:
    temp = input().split(" ")
    if(temp[0] == "0" and temp[1] == "0"):
        break
    inputs.append(temp)
    
for i in range(len(inputs)):
    print(int(inputs[i][0])+int(inputs[i][1]))
```

Note that input will raise a StopIteration error once there is is no more input. In your case you can fix this by ending with `0 0`, so the loop is broken before you hit the StopIteration.

```python
standard_input = ['1 1', '1 1', '0 0']
inputs = []
while True:
    temp = input().split(" ")
    if(temp[0] == "0" and temp[1] == "0"):
        break
    inputs.append(temp)
    
for i in range(len(inputs)):
    print(int(inputs[i][0])+int(inputs[i][1]))
```
