### ISSUE TITLE
https://github.com/Almenon/AREPL-vscode/issues/253#issue-445746922

### ISSUE THREAD

**Issue by sam6666525** [Almenon/AREPL-vscode#433]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Other Information (please complete the following information):**
 - OS: [e.g. Windows10]
 - Python Version [e.g. 22]

**Additional context**

**Comment by Almenon** [comment]
What's the problem you ran into?

**Comment by Almenon** [comment]
No reponse, closing
