### ISSUE TITLE
Pandas not formatted correctly in repl

### ISSUE THREAD

**Issue by gkatsanos** [Almenon/AREPL-vscode#434]
**Describe the bug**

**To Reproduce**
create a panda Series
obj = pd.Series(['George', 'Nick', 'John'], index=['a', 'b', 'c'])

inspect AREPL:
![image](https://user-images.githubusercontent.com/1768834/195634776-40d1d837-d4b0-4d44-9dc6-91ac134e289c.png)

**Expected behavior**
should be printed formatted:
```
>>> obj
a    George
b      Nick
c      John
dtype: object
```
command line repl:
![image](https://user-images.githubusercontent.com/1768834/195634820-cdacc697-d909-4268-a3fd-a6fe6fa1e7c2.png)

Python 3.10

**Comment by Almenon** [comment]
The variables section of the code shows you the properties of the variable. If you want to see the variable in string format you need to print it out.
