### ISSUE TITLE
warning 

### ISSUE THREAD

**Issue by youjunxiaji** [Almenon/AREPL-vscode#436]
when i import numpy,AREPL will give me warning message.And how i deal with the problem?
![Snipaste_2022-11-24_10-30-51](https://user-images.githubusercontent.com/94896689/203680993-96eb77e6-2674-4733-89a0-30ddf04798e8.png)

**Comment by StohanzlMart** [comment]
I had a "nnumpy" folder in my downloads, idk how it got there, but when I removed it, that warning was gone :P

**Comment by youjunxiaji** [comment]
> 

Sorry i can't find this "nnumpy" folder and i am not good at English.So what's "idk" mean? : - )

**Comment by StohanzlMart** [comment]
I don't know :)

Maybe it's somewhere else on your pc... just search for it.

**Comment by youjunxiaji** [comment]
> 
Okay. Thanks for you replying.

**Comment by Almenon** [comment]
This should be fixed if you upgrade to AREPL v3 :)
