### ISSUE TITLE
Numpy is reloaded a second time - UserWarning

### ISSUE THREAD

**Issue by lucadardi** [Almenon/AREPL-vscode#440]
**Describe the bug**
__warningregistry__:('The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.', <class 'UserWarning'>, 1): true,
 
This error shows up all the time, despite of the package I import (I can import Pandas and see the message for the Numpy). I'm using VS Code, Python 3.11.1 and Anaconda.

I have installed and reinstalled either Python, Anaconda and the extension. 
I have searched all around for any duplicate folders from previous installations, it's clean.
Checked the PATH and they point only to one installation.

**To Reproduce**
1. Import any package
2. See UserWarning

**Expected behavior**
No warning, as the codes works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/124458096/216781194-c2636997-87e9-4747-941e-6b6cfaf6dbeb.png)
**Other Information (please complete the following information):**
 - OS: Windows 11

**Comment by Almenon** [comment]
This is a known issue, sorry. Please follow https://github.com/Almenon/AREPL-vscode/issues/439 for updates.
