### ISSUE TITLE
Not working with import local file/module in same dir?

### ISSUE THREAD

**Issue by goyalyashpal** [Almenon/AREPL-vscode#445]
**Describe the bug**
AREPL doesn't seem to recognise the local module/python file in same directory
Whereas, the VSCodium is showing preview properly, which means that the import etc is otherwise okay.

Also, in output, under the variables, AREPL is showing this:

```
    queue: graphs.hanginglist = graphs.hanginglist([source])
```

![image](https://user-images.githubusercontent.com/19423063/231756679-8fcd6b08-7550-4812-8797-913d79d479b8.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Other Information (please complete the following information):**
 - OS: Win 10 22H2
 - Python Version: 3.11.2

**Additional context**

**Comment by Almenon** [comment]
AREPL should work with locally imported files. Please upload the code you're using.

**Comment by goyalyashpal** [comment]
as can be seen in abive highlight, arepl aint updating very well...

i have removed the colon from file, but arepl is still showing stuck on that

**Comment by Almenon** [comment]
I need your exact code to reproduce the issue on my machine because last time I checked on my machine local file imports worked, but I have different code.

**Comment by goyalyashpal** [comment]
it seems to me that arepl was working fine as long as ms-python was unable to recognise the python interpretter.

now that ms-python has identified the interprettor, arepl is glitching a lot, and not at all updating :(
