### ISSUE TITLE
[FEAT] Run CI tests on macOS

### ISSUE THREAD

**Issue by Panquesito7** [Almenon/AREPL-vscode#452]
**Is your feature request related to a problem? Please describe.**

The current CI tests only run on Windows and Linux. However, it doesn't run on macOS.
By running it on macOS, you'll ensure everything is working as expected in the three major operating systems. The more tests there are, the better, IMO.

**Describe the solution you'd like**

Add macOS tests on the CI.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Almenon** [comment]
Linux is similar enough to Mac that I don't see this as worth the effort, to be honest. You're still free to submit a PR for this if you wish. Not to discourage you from thinking of improvements, ideas are always welcome :)

**Comment by Panquesito7** [comment]
That's true, it is very similar to macOS.
I think I'll create a PR. It doesn't harm testing it in another operating system, it is even better, IMO.

Thank you. 🙂
