### ISSUE TITLE
Error in the AREPL extension! err code: 3221225781

### ISSUE THREAD

**Issue by Puneetha-20** [Almenon/AREPL-vscode#459]
In order to run the program in visual studio code maximum I prefer to run the python code AREPL extension but I am getting AREPL extension error code of 3221225781. How to fix these problem.
<img width="199" alt="image" src="https://github.com/Almenon/AREPL-vscode/assets/155239482/5d017fd8-d090-406e-b82a-f57eaf2ad174">

**Comment by Almenon** [comment]
I think the python version you are using might be corrupted. I would try pointing the extension to a different python version. First try running python from your terminal - does that work? If not, I would fix that.

**Comment by Puneetha-20** [comment]
> I think the python version you are using might be corrupted. I would try pointing the extension to a different python version. First try running python from your terminal - does that work? If not, I would fix that.

Thank you for this my problem was solved
