### ISSUE TITLE
false reading/ indication of wrong object

### ISSUE THREAD

**Issue by Grissy0** [Almenon/AREPL-vscode#461]
![Screenshot 2024-04-24 17 11 31](https://github.com/Almenon/AREPL-vscode/assets/97944897/3121e0c2-e412-4653-b72c-8eed82775d49)
**Describe the bug**
The code evaluated falsely according to pybites.
It is one of their code bits that is in their learning section.

**To Reproduce**

**Expected behavior**
The screenshot depicts exactly what pybites code is, on right the arepl indicated an error. Who is right?

**Screenshots**

**Other Information (please complete the following information):**
 - OS: [e.g. Windows10]
 - Python Version [e.g. 22]

**Additional context**

**Comment by Almenon** [comment]
lstrip is not a function in Python as far as I'm aware.  Try opening up a regular python console or using python in https://repl.it, you will get an error there too.
