### ISSUE TITLE
I am a Python language biggener and I have aproblem with my VS code that the code does'nt run! what do you think the problem and its solution

### ISSUE THREAD

**Issue by enanymoh** [Almenon/AREPL-vscode#463]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Other Information (please complete the following information):**
 - OS: [e.g. Windows10]
 - Python Version [e.g. 22]

**Additional context**

**Comment by Almenon** [comment]
What is your code, the error you are getting, and your variables?
