### ISSUE TITLE
How to Prevent Automatic Line Wrapping When Content Exceeds Screen Width?

### ISSUE THREAD

**Issue by FuYiGuang123** [Almenon/AREPL-vscode#467]
Hello everyone,

I'm facing a challenge with CSS where I need to prevent text from wrapping automatically when it exceeds the width of the screen. I want the text to continue on the same line and provide a horizontal scrollbar if necessary. Here's what I've tried so far:

Set white-space: nowrap; to keep the text on a single line.
Used overflow-x: auto; to add a horizontal scrollbar when the content overflows.
Despite these settings, I'm still encountering issues where the text doesn't behave as expected. It either wraps onto the next line or doesn't display a scrollbar when needed. Here is the CSS I'm currently using:
![image](https://github.com/user-attachments/assets/2bb89a92-f3bd-4415-a51c-18cec5e584ba)

* {
  white-space: nowrap;
  overflow-x: auto;
}

Could anyone suggest what might be going wrong or provide alternative solutions to achieve this effect? Any help would be greatly appreciated!

Thank you!

**Comment by Almenon** [comment]
You're missing the CSS selector. The print results are in a div with class "print". You can find this out using the "Developer: Open Webview Developer Tools" command and inspecting the element. You can then add a selector to target the div like so:

```
.print {white-space: nowrap; }
```
