### ISSUE TITLE
Without Any reason AREPL is showing Indentation Error

### ISSUE THREAD

**Issue by IshanDeyYT** [Almenon/AREPL-vscode#468]
**After writting this code:**
```python
keepgoing = True
x = 100
while keepgoing:
    print(x)
    x = x - 10
    if x < 50:
        keepgoing = False
```

![Untitled](https://github.com/user-attachments/assets/a1f4ffad-00dc-41cd-a406-687283c18eff)

But If I run it in TERMINAL then the output will be:
100
90
80
70
60
50

**Comment by Almenon** [comment]
It works for me. Maybe try closing and re-opening AREPL?

**Comment by Almenon** [comment]
No response, closing
