### ISSUE TITLE
Does not work with asyncio 

### ISSUE THREAD

**Issue by HQupgradeHQ** [Almenon/AREPL-vscode#60]
version of python - 3 
windows
<details><summary>screenshot </summary><p>

![asycn](https://user-images.githubusercontent.com/18361586/39894256-eb1b61fa-54ae-11e8-9362-cc0d7f68e530.gif)

</p></details>
:v:

**Comment by Almenon** [comment]
Wow, I didn't know anyone actually used the electron app.  You're the first user I know of, congrats! :D

What is not working specifically? And can you paste the example in here as text please?

I'm at pycon this week so I will be busy but I will look into it as soon as I get back :)

**Comment by HQupgradeHQ** [comment]
Asyncio loop should run those iterations immediately , and throw print statements ASAP , but this doesn't happen. Instead AREPL waiting for all of tasks to complete and only then printing all results .

**Comment by Almenon** [comment]
Ah, so you want it to print in real-time.  I've already implemented this (see https://github.com/Almenon/AREPL/issues/68) but I have not released it yet.  I'll let you know when I release a new version and keep this issue open untill I do so.  I'll get to it by this Sunday.

**Comment by Almenon** [comment]
done - see https://github.com/Almenon/AREPL/releases/tag/v1.0.0-alpha.8
