### ISSUE TITLE
AREPL fails in Code 1.23

### ISSUE THREAD

**Issue by SheepDomination** [Almenon/AREPL-vscode#61]
As of updating Visual Studio Code 1.23 AREPL does not work when selecting some code followed by `F1` & `AREPL: Open Highlighted code in new AREPL session` ?

**Comment by Almenon** [comment]
Thanks for the bug report!  What platform did you encounter this error on (windows / mac / linux) ?

**Comment by Almenon** [comment]
Also if you go to help -> toggle developer tools is there any errors logged there?

**Comment by SheepDomination** [comment]
Platform is Windows, and yes there are errors logged in the console.  The error is; `extension.newAREPLSessionOnHighlightedCode' not found`

**Comment by Almenon** [comment]
That doesn't really tell me much (not your fault, javascript logging in general is not very helpful).  What do the other errors say?

The error is very odd because I just upgraded VSCode to latest and did not get that error.

If you go to help -> about what version of VSCode does it say?  I am on 1.23.1

Also what version of python do you have?  You can find out by doing python --version from the command line.

**Comment by SheepDomination** [comment]
Same version of VS Code as yourself 1.23.1.  I'm experiencing another odd problem with VS Code, I wonder if they are related.  Python `2.7.13`.

**Comment by Almenon** [comment]
Ohhh that might be your issue.  AREPL is only for Python 3.

Python 2 will no longer be supported as of 2020.

**Comment by Almenon** [comment]
(any version of python 3 should work, but preferably 3.5 or above)

**Comment by SheepDomination** [comment]
@Almenon Updated my last post; I make a mistake on the version, sorry.

**Comment by Almenon** [comment]
Wierd - if you have python 3.6 and it is in your PATH it should work.  What was the other odd problem you experienced?

**Comment by SheepDomination** [comment]
I got it working quite well actually 👍  
Although, when running `AREPL: Open Highlighted code in new AREPL session` it would be good if it didn't create new documents within VSCode and rather wrote to a temporary file of sorts to which I could then load. Especially if experimenting to analyze code snippets etc.

Also can *AREPL* work with PyQT and the like ?

**Comment by Almenon** [comment]
Yes, AREPL supports PyQT :)

Currently it supports a hardcoded list of GUI libraries

> ["turtle", "matplotlib", "tkinter", "kivy", "pyforms", "PyQt4", "PyQt5", "wx", "pyside", "plotly", "ggplot", "bokeh"]

With the next release I'll turn that into a setting you can change.

It will work with any GUI library in the list but there's two things to watch out for:
1. The window will steal your focus whenever it pops up.  On windows you can use alt-tab to quickly switch back to VSCode
2. The window might pop up over your code - you should adjust the position of the window so it appears where you want it.

```
import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtGui import QIcon
 
class App(QWidget):
 
    def __init__(self):
        super().__init__()
        self.title = 'PyQt5 simple window - pythonspot.com'
        self.left = 900 # adjust these values so popup doesnt appear over your code
        self.top = 100
        self.width = 640
        self.height = 480
        self.initUI()
 
    def initUI(self):
        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)
        self.show()

app = QApplication(sys.argv)
ex = App()
app.exec()
```

As for the `AREPL: Open Highlighted code in new AREPL session` command, I made it create a new document so you don't end up with junk temporary files in your directory.  Now that I think about it what I could do instead is save the new document to a folder like "%Appdata%\AREPL" so you can save and load your snippets from there.  Does that sound better?

**Comment by SheepDomination** [comment]
> Now that I think about it what I could do instead is save the new document to a folder like "%Appdata%\AREPL" so you can save and load your snippets from there. Does that sound better?

What about compiling all the snippets to one file separated by date and time; otherwise if not, your suggestion is good.
