### ISSUE TITLE
command 'extension.evalPythonInRealTime' not found

### ISSUE THREAD

**Issue by alitekdemir** [Almenon/AREPL-vscode#88]
[exthost1.log](https://github.com/Almenon/AREPL-vscode/files/2239158/exthost1.log)

**Comment by Almenon** [comment]
The log doesn't give me any information, unfortunately.  But you might be experiencing the same problem as #81, in which case you just need to install a python package at the user level (for example, pip install requests --user).  Or you can wait for me to fix it which should be done soon.

**Comment by Almenon** [comment]
Sorry forgot about this issue.  I fixed [it](https://github.com/Almenon/AREPL-vscode/issues/81) a while ago.

If you try opening AREPL again do you still have the same problem?
